
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (100, 'Crash', 'Musical', 'Ulrike Do Rosario', to_date('24-07-2019', 'dd-mm-yyyy'), 102, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (101, 'Notorious', 'Animation', 'Chanda Stirland', to_date('15-02-2017', 'dd-mm-yyyy'), 107, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (102, 'Giant', 'Biography', 'Dwight Lopez', to_date('02-02-2014', 'dd-mm-yyyy'), 108, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (103, 'Moana', 'Comedy', 'Grannie Brosnan', to_date('11-03-2007', 'dd-mm-yyyy'), 148, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (104, 'Deadpool', 'Fantasy', 'Lenard Pothergill', to_date('20-01-2002', 'dd-mm-yyyy'), 124, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (105, 'Gandhi', 'Action', 'Kele Hastin', to_date('31-12-2010', 'dd-mm-yyyy'), 94, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (106, 'Jumper', 'Documentary', 'Merlina Venables', to_date('21-06-2014', 'dd-mm-yyyy'), 76, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (107, 'Maverick', 'Fantasy', 'Zack Jeandet', to_date('22-07-2018', 'dd-mm-yyyy'), 61, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (108, 'Thor', 'Crime', 'Albertine Sedgwick', to_date('18-01-2016', 'dd-mm-yyyy'), 112, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (109, 'Iron Man', 'Comedy', 'Nefen Bruyett', to_date('06-03-2017', 'dd-mm-yyyy'), 169, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (110, 'Crash', 'Biography', 'Ninnetta Klewi', to_date('10-09-2022', 'dd-mm-yyyy'), 180, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (111, 'Star Trek', 'Action', 'Kirstin Meas', to_date('24-03-2012', 'dd-mm-yyyy'), 94, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (112, 'Brave', 'Horror', 'Farly Haverty', to_date('29-01-2011', 'dd-mm-yyyy'), 129, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (113, 'Witness', 'Sport', 'Bruce Shrimpton', to_date('05-01-2021', 'dd-mm-yyyy'), 82, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (114, 'Zombieland', 'Biography', 'Felecia Simoneschi', to_date('31-05-2001', 'dd-mm-yyyy'), 177, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (115, 'Dumbo', 'Comedy', 'Avictor Hews', to_date('02-05-2015', 'dd-mm-yyyy'), 127, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (116, 'Clerks', 'Comedy', 'Nada Cogar', to_date('01-07-2003', 'dd-mm-yyyy'), 114, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (117, 'Amelie', 'Thriller', 'Ossie Ilyushkin', to_date('22-07-2012', 'dd-mm-yyyy'), 176, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (118, 'Trumbo', 'Documentary', 'Maisey Haughton', to_date('30-06-2009', 'dd-mm-yyyy'), 111, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (119, 'Rio', 'Romance', 'Reiko Bucher', to_date('11-09-2008', 'dd-mm-yyyy'), 144, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (120, 'Black Swan', 'Adventure', 'Esta Papen', to_date('14-06-2005', 'dd-mm-yyyy'), 114, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (121, 'Goonies', 'Sport', 'Philippe Conradie', to_date('05-03-2009', 'dd-mm-yyyy'), 99, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (122, 'Rio', 'Documentary', 'Norman Deadman', to_date('22-12-2015', 'dd-mm-yyyy'), 73, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (123, 'Twister', 'Horror', 'Ursola Masson', to_date('27-03-2022', 'dd-mm-yyyy'), 64, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (124, 'Jaws', 'Adventure', 'Kizzie Keepin', to_date('17-01-2008', 'dd-mm-yyyy'), 91, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (125, 'Singles', 'Romance', 'Gene Fulloway', to_date('25-11-2006', 'dd-mm-yyyy'), 149, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (126, 'Contact', 'Action', 'Lark Wolfindale', to_date('04-12-2009', 'dd-mm-yyyy'), 106, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (127, 'Witness', 'Biography', 'Patty Teasdale', to_date('16-08-2001', 'dd-mm-yyyy'), 89, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (128, 'Shrek', 'Fantasy', 'Blane Edge', to_date('11-12-2020', 'dd-mm-yyyy'), 109, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (129, 'Superbad', 'Sci-Fi', 'Filbert Muzzollo', to_date('09-11-2007', 'dd-mm-yyyy'), 111, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (130, 'Watchmen', 'Adventure', 'Ana England', to_date('19-07-2000', 'dd-mm-yyyy'), 62, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (131, 'Trumbo', 'Horror', 'Mallorie Lilly', to_date('06-09-2004', 'dd-mm-yyyy'), 120, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (132, 'Shrek', 'History', 'Aldis Luton', to_date('28-11-2004', 'dd-mm-yyyy'), 125, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (133, 'Gandhi', 'War', 'Lorraine Bothbie', to_date('18-04-2013', 'dd-mm-yyyy'), 89, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (134, 'Matilda', 'Comedy', 'Manolo Vasilkov', to_date('12-11-2009', 'dd-mm-yyyy'), 87, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (135, 'Dumbo', 'Family', 'Rebekkah Leverette', to_date('07-06-2004', 'dd-mm-yyyy'), 72, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (136, 'Jumanji', 'Drama', 'Roseann Esmond', to_date('01-08-2016', 'dd-mm-yyyy'), 81, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (137, 'Star Trek', 'Thriller', 'Giacobo Carty', to_date('14-04-2013', 'dd-mm-yyyy'), 116, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (138, 'Gandhi', 'Thriller', 'Patton Bussy', to_date('30-07-2009', 'dd-mm-yyyy'), 103, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (139, 'Bolt', 'Thriller', 'Ophelie Ertel', to_date('01-03-2013', 'dd-mm-yyyy'), 144, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (140, 'Superbad', 'Sci-Fi', 'Peri Lambkin', to_date('19-02-2014', 'dd-mm-yyyy'), 138, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (141, 'Looper', 'Biography', 'Benn Richings', to_date('29-07-2013', 'dd-mm-yyyy'), 97, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (142, 'Cop Land', 'Thriller', 'Vasilis Hannum', to_date('18-05-2020', 'dd-mm-yyyy'), 87, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (143, 'Selma', 'Documentary', 'Gordie Chilley', to_date('20-11-2020', 'dd-mm-yyyy'), 118, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (144, 'Rushmore', 'Mystery', 'Sindee Chieze', to_date('10-05-2002', 'dd-mm-yyyy'), 155, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (145, 'Xanadu', 'Thriller', 'Tedie Benne', to_date('30-03-2005', 'dd-mm-yyyy'), 174, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (146, 'Erin Brock', 'Mystery', 'Elwood Nelissen', to_date('05-02-2013', 'dd-mm-yyyy'), 108, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (147, 'Witness', 'Sci-Fi', 'Brion Fellows', to_date('16-07-2010', 'dd-mm-yyyy'), 97, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (148, 'Gandhi', 'Family', 'Rabi Champley', to_date('07-03-2003', 'dd-mm-yyyy'), 172, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (149, 'Jumper', 'Sport', 'Pietra Folshom', to_date('20-02-2019', 'dd-mm-yyyy'), 162, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (150, 'Tombstone', 'Sci-Fi', 'Mike Grimsell', to_date('13-05-2021', 'dd-mm-yyyy'), 122, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (151, 'Speed', 'Thriller', 'Graehme Presnail', to_date('05-06-2008', 'dd-mm-yyyy'), 151, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (152, 'Hancock', 'Mystery', 'Aylmer Crombie', to_date('03-11-2002', 'dd-mm-yyyy'), 104, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (153, 'Gandhi', 'Sci-Fi', 'Abra Parkisson', to_date('18-11-2003', 'dd-mm-yyyy'), 67, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (154, 'Gandhi', 'Western', 'Nevile Waterfall', to_date('03-09-2022', 'dd-mm-yyyy'), 125, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (155, 'Deadpool', 'Musical', 'Enrichetta Goff', to_date('12-07-2006', 'dd-mm-yyyy'), 138, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (156, 'Gremlins', 'Western', 'Kelsi Blayd', to_date('28-11-2021', 'dd-mm-yyyy'), 136, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (157, 'Memento', 'War', 'Corrine Pannett', to_date('17-06-2009', 'dd-mm-yyyy'), 86, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (158, 'Rushmore', 'Romance', 'Audi Kubacki', to_date('24-08-2007', 'dd-mm-yyyy'), 65, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (159, 'The Mask', 'Sport', 'Gwenette Physick', to_date('22-11-2010', 'dd-mm-yyyy'), 78, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (160, 'Speed', 'Drama', 'Raff Manus', to_date('03-02-2007', 'dd-mm-yyyy'), 174, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (161, 'Twister', 'History', 'Natal Haslock', to_date('17-05-2011', 'dd-mm-yyyy'), 145, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (162, 'X-', 'Mystery', 'Kaitlyn Kibbey', to_date('01-12-2003', 'dd-mm-yyyy'), 108, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (163, 'Rocky', 'Adventure', 'Sunshine Veazey', to_date('05-07-2022', 'dd-mm-yyyy'), 79, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (164, 'Coraline', 'Western', 'Drucill Beaves', to_date('23-10-2004', 'dd-mm-yyyy'), 127, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (165, 'Gattaca', 'Sci-Fi', 'Sherry Cawood', to_date('17-05-2015', 'dd-mm-yyyy'), 134, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (166, 'Nim''s Island', 'Drama', 'Gwendolyn Howes', to_date('27-02-2023', 'dd-mm-yyyy'), 124, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (167, 'Deadpool', 'Documentary', 'Sammy Madrell', to_date('03-12-2012', 'dd-mm-yyyy'), 93, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (168, 'Lincoln', 'Sci-Fi', 'Mendie Mushet', to_date('28-06-2015', 'dd-mm-yyyy'), 75, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (169, 'Coco', 'Western', 'Farly Dumbelton', to_date('25-03-2016', 'dd-mm-yyyy'), 148, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (170, 'Casino', 'Biography', 'Bogart Burle', to_date('21-03-2016', 'dd-mm-yyyy'), 127, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (171, 'Gattaca', 'History', 'Shir Redman', to_date('16-09-2020', 'dd-mm-yyyy'), 166, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (172, 'Moana', 'Drama', 'Astrid Cinelli', to_date('09-03-2002', 'dd-mm-yyyy'), 149, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (173, 'Aliens', 'Horror', 'Annamaria Ismead', to_date('11-11-2002', 'dd-mm-yyyy'), 160, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (174, 'Dumbo', 'Adventure', 'Consuelo Impey', to_date('12-10-2021', 'dd-mm-yyyy'), 83, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (175, 'Risen', 'Animation', 'Sharla Dorcey', to_date('14-08-2011', 'dd-mm-yyyy'), 105, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (176, 'Whiplash', 'Biography', 'Nadia Peddowe', to_date('11-08-2007', 'dd-mm-yyyy'), 106, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (177, 'Poltergeist', 'Biography', 'Sterling Ingles', to_date('09-11-2012', 'dd-mm-yyyy'), 84, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (178, 'Doubt', 'History', 'Venus Bumfrey', to_date('06-02-2011', 'dd-mm-yyyy'), 135, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (179, 'Twister', 'Drama', 'Cletus Staley', to_date('02-03-2015', 'dd-mm-yyyy'), 163, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (180, 'Zoolander', 'Crime', 'Frieda McGorley', to_date('09-01-2015', 'dd-mm-yyyy'), 87, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (181, 'Sin City', 'Fantasy', 'Gard Vannoort', to_date('25-10-2014', 'dd-mm-yyyy'), 89, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (182, 'Ali', 'Adventure', 'Felipe Bignal', to_date('07-11-2005', 'dd-mm-yyyy'), 145, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (183, 'Chappie', 'Sport', 'Gustavus Wilbor', to_date('26-04-2016', 'dd-mm-yyyy'), 156, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (184, 'Risen', 'Sci-Fi', 'Jemimah Aldritt', to_date('10-09-2020', 'dd-mm-yyyy'), 163, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (185, 'Thor', 'Documentary', 'Thorvald Bagenal', to_date('11-09-2011', 'dd-mm-yyyy'), 172, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (186, 'Avatar', 'Romance', 'Joline Picford', to_date('04-09-2000', 'dd-mm-yyyy'), 73, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (187, 'Iron Man', 'Romance', 'Sargent Collar', to_date('06-08-2017', 'dd-mm-yyyy'), 160, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (188, 'Godzilla', 'Crime', 'Ivor Halshaw', to_date('11-07-2002', 'dd-mm-yyyy'), 60, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (189, 'Maverick', 'Sport', 'Hirsch Becks', to_date('18-11-2001', 'dd-mm-yyyy'), 115, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (190, 'Chocolat', 'Biograp', 'Sam Antoniewicz', to_date('07-04-2012', 'dd-mm-yyyy'), 127, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (191, 'Moana', 'Thriller', 'Witty Zimmerman', to_date('11-05-2013', 'dd-mm-yyyy'), 113, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (192, 'Casino', 'Adventure', 'Lynelle Adnams', to_date('04-08-2002', 'dd-mm-yyyy'), 67, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (193, 'Witness', 'Thriller', 'Aida Tourne', to_date('26-10-2019', 'dd-mm-yyyy'), 120, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (194, 'Sideways', 'Western', 'Pris Brach', to_date('09-08-2009', 'dd-mm-yyyy'), 90, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (195, 'Matilda', 'Drama', 'Cord MacKnockiter', to_date('10-05-2004', 'dd-mm-yyyy'), 119, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (196, 'Elf', 'Sport', 'Rabbi Pershouse', to_date('11-05-2013', 'dd-mm-yyyy'), 146, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (197, 'Rocky', 'Horror', 'Joey Aitken', to_date('17-06-2006', 'dd-mm-yyyy'), 90, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (198, 'Moonlight', 'Sci-Fi', 'Randi Pattini', to_date('02-09-2008', 'dd-mm-yyyy'), 69, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (199, 'Labyrinth', 'Mystery', 'Olly Schubuser', to_date('09-04-2014', 'dd-mm-yyyy'), 133, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (200, 'Moon', 'Horror', 'Margarethe De Simoni', to_date('30-05-2011', 'dd-mm-yyyy'), 116, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (201, 'Contact', 'Comedy', 'Katleen Fermor', to_date('06-07-2014', 'dd-mm-yyyy'), 72, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (202, 'Unforgiven', 'Sport', 'Isidro Marini', to_date('30-03-2004', 'dd-mm-yyyy'), 78, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (203, 'Ant-Man', 'Fantasy', 'Albie Cheak', to_date('12-12-2014', 'dd-mm-yyyy'), 71, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (204, 'Trumbo', 'Sci-Fi', 'Ola Quantick', to_date('23-12-2022', 'dd-mm-yyyy'), 180, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (205, 'Frida', 'Animation', 'Batholomew Rains', to_date('14-03-2005', 'dd-mm-yyyy'), 133, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (206, 'Hancock', 'Biography', 'Jenni Fantin', to_date('27-05-2013', 'dd-mm-yyyy'), 117, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (207, 'Gandhi', 'Mystery', 'Spence Orwell', to_date('13-04-2007', 'dd-mm-yyyy'), 146, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (208, 'Amelie', 'War', 'Benni Gergely', to_date('20-05-2016', 'dd-mm-yyyy'), 79, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (209, 'Witness', 'War', 'Cathe Kulver', to_date('25-12-2000', 'dd-mm-yyyy'), 142, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (210, 'Sideways', 'Romance', 'Fara Bumby', to_date('26-01-2021', 'dd-mm-yyyy'), 140, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (211, 'Rocky', 'Romance', 'Whit Welfair', to_date('24-11-2015', 'dd-mm-yyyy'), 180, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (212, 'Twister', 'Crime', 'Aloise Boom', to_date('02-05-2023', 'dd-mm-yyyy'), 111, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (213, 'Giant', 'Drama', 'Luke Strognell', to_date('04-10-2019', 'dd-mm-yyyy'), 81, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (214, 'Whiplash', 'Crime', 'Bobbye Durnall', to_date('07-04-2020', 'dd-mm-yyyy'), 66, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (215, 'Zombieland', 'War', 'Saunders Purbrick', to_date('21-06-2023', 'dd-mm-yyyy'), 108, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (216, 'Fargo', 'Animation', 'Giralda Oyley', to_date('04-12-2000', 'dd-mm-yyyy'), 96, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (217, 'Giant', 'Adventure', 'Lorain Buttrick', to_date('07-06-2019', 'dd-mm-yyyy'), 100, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (218, 'Black Swan', 'Musical', 'Luce Rantoull', to_date('30-08-2004', 'dd-mm-yyyy'), 68, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (219, 'Twister', 'Fantasy', 'Zitella Baxstair', to_date('14-03-2019', 'dd-mm-yyyy'), 166, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (220, 'Paprika', 'Sci-Fi', 'Lolly McIlenna', to_date('22-12-2021', 'dd-mm-yyyy'), 152, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (221, 'Fargo', 'Musical', 'Powell Remmer', to_date('10-02-2011', 'dd-mm-yyyy'), 88, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (222, 'Rushmore', 'History', 'Ronny Brownsmith', to_date('16-02-2013', 'dd-mm-yyyy'), 120, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (223, 'Witness', 'Romance', 'Etta Sackett', to_date('28-11-2022', 'dd-mm-yyyy'), 110, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (224, 'Bolt', 'Fantasy', 'Ivar Riddoch', to_date('13-02-2024', 'dd-mm-yyyy'), 179, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (225, 'Beetlejuice', 'Action', 'Eunice Goligher', to_date('21-11-2017', 'dd-mm-yyyy'), 179, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (226, 'Chocolat', 'Animation', 'Isaak Frye', to_date('24-10-2020', 'dd-mm-yyyy'), 108, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (227, 'Paprika', 'Adventure', 'Jeanne Dafforne', to_date('21-09-2016', 'dd-mm-yyyy'), 78, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (228, 'Signs', 'Crime', 'Chelsie Thorneley', to_date('12-12-2018', 'dd-mm-yyyy'), 159, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (229, 'Amelie', 'Drama', 'Esra Bretelle', to_date('17-03-2012', 'dd-mm-yyyy'), 112, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (230, 'Up', 'Comedy', 'Ciro Ellesmere', to_date('15-02-2001', 'dd-mm-yyyy'), 140, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (231, 'Signs', 'Animation', 'Torrance Dobrowlski', to_date('17-08-2014', 'dd-mm-yyyy'), 104, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (232, 'Whiplash', 'Horror', 'Lamar Adnett', to_date('18-06-2023', 'dd-mm-yyyy'), 146, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (233, 'Coraline', 'Drama', 'Lib Frost', to_date('29-01-2020', 'dd-mm-yyyy'), 71, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (234, 'Moon', 'Western', 'Ulrick Skrzynski', to_date('05-04-2009', 'dd-mm-yyyy'), 169, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (235, 'Memento', 'Biography', 'Adriano Chapling', to_date('26-08-2019', 'dd-mm-yyyy'), 175, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (236, 'Gigi', 'Adventure', 'Otto Schrir', to_date('06-04-2020', 'dd-mm-yyyy'), 137, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (237, 'Gremlins', 'Drama', 'Nell Augur', to_date('21-09-2016', 'dd-mm-yyyy'), 99, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (238, 'Wild', 'Animation', 'Janis Normanton', to_date('29-05-2012', 'dd-mm-yyyy'), 177, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (239, 'Clerks', 'Action', 'Olivero Djordjevic', to_date('25-07-2001', 'dd-mm-yyyy'), 112, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (240, 'Superbad', 'Thriller', 'Karlis De Goey', to_date('26-02-2005', 'dd-mm-yyyy'), 163, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (241, 'Thor', 'Sport', 'Ethelbert Pelman', to_date('16-04-2019', 'dd-mm-yyyy'), 141, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (242, 'Thor', 'Thriller', 'Bruno Plaster', to_date('01-04-2018', 'dd-mm-yyyy'), 117, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (243, 'Avatar', 'Documentary', 'Randy Truscott', to_date('05-05-2010', 'dd-mm-yyyy'), 98, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (244, 'Erin Brock', 'Horror', 'Randy Benedettini', to_date('11-05-2012', 'dd-mm-yyyy'), 146, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (245, 'Spartacus', 'Horror', 'Kamilah Beckerleg', to_date('02-09-2008', 'dd-mm-yyyy'), 164, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (246, 'Matilda', 'Action', 'Erv Syrie', to_date('04-01-2012', 'dd-mm-yyyy'), 72, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (247, 'Scarface', 'Family', 'Walden Proger', to_date('05-01-2007', 'dd-mm-yyyy'), 154, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (248, 'Hercules', 'Horror', 'Allegra Connett', to_date('08-12-2002', 'dd-mm-yyyy'), 94, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (249, 'Labyrinth', 'Sport', 'Dew Norway', to_date('02-07-2020', 'dd-mm-yyyy'), 111, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (250, 'Titanic', 'Comedy', 'Elayne Markwick', to_date('05-08-2005', 'dd-mm-yyyy'), 167, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (251, 'Babe', 'History', 'Alison Fellibrand', to_date('14-02-2012', 'dd-mm-yyyy'), 156, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (252, 'Ratatouille', 'War', 'Colly Novic', to_date('02-09-2017', 'dd-mm-yyyy'), 179, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (253, 'Risen', 'War', 'Cordula Lehrer', to_date('16-06-2006', 'dd-mm-yyyy'), 99, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (254, 'Patton', 'History', 'Briggs Lortzing', to_date('18-12-2007', 'dd-mm-yyyy'), 141, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (255, 'Singles', 'Horror', 'Amanda Gerwood', to_date('01-05-2010', 'dd-mm-yyyy'), 108, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (256, 'Black Swan', 'Action', 'Aaren Mangan', to_date('13-03-2018', 'dd-mm-yyyy'), 122, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (257, 'Contact', 'Thriller', 'Octavius Kinneir', to_date('28-06-2020', 'dd-mm-yyyy'), 89, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (258, 'Rudy', 'Animation', 'Avrit Janata', to_date('18-04-2010', 'dd-mm-yyyy'), 127, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (259, 'Casino', 'Action', 'Finlay Swalteridge', to_date('07-12-2016', 'dd-mm-yyyy'), 96, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (260, 'Rushmore', 'Musical', 'Alonzo Pavy', to_date('23-01-2021', 'dd-mm-yyyy'), 103, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (261, 'Zoolander', 'Adventure', 'Giffard Naire', to_date('10-04-2012', 'dd-mm-yyyy'), 149, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (262, 'Gravity', 'Family', 'Clair Bantock', to_date('22-11-2023', 'dd-mm-yyyy'), 131, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (263, 'Paprika', 'Sci-Fi', 'Issie Olrenshaw', to_date('20-09-2016', 'dd-mm-yyyy'), 156, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (264, 'Psycho', 'Adventure', 'Alfi Hammerberger', to_date('07-09-2023', 'dd-mm-yyyy'), 162, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (265, 'Labyrinth', 'Fantasy', 'Marian Lutsch', to_date('13-02-2010', 'dd-mm-yyyy'), 135, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (266, 'Thor', 'War', 'Kerrill Highton', to_date('09-04-2023', 'dd-mm-yyyy'), 122, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (267, 'Unbroken', 'Adventure', 'Iolande Comusso', to_date('13-06-2023', 'dd-mm-yyyy'), 60, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (268, 'Dumbo', 'Musical', 'Wilt Margarson', to_date('27-02-2020', 'dd-mm-yyyy'), 130, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (269, 'Jaws', 'Thriller', 'Marylinda Copas', to_date('05-05-2021', 'dd-mm-yyyy'), 82, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (270, 'Bolt', 'Crime', 'Raynell Lamminam', to_date('22-08-2001', 'dd-mm-yyyy'), 164, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (271, 'Shutter', 'Comedy', 'Jolene Denisevich', to_date('17-05-2002', 'dd-mm-yyyy'), 97, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (272, 'Spartacus', 'Mystery', 'Ardyce Beckensall', to_date('08-02-2022', 'dd-mm-yyyy'), 132, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (273, 'Matilda', 'Western', 'Kathi Castillon', to_date('19-06-2012', 'dd-mm-yyyy'), 172, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (274, 'Hackers', 'Action', 'Alina Liddel', to_date('20-04-2021', 'dd-mm-yyyy'), 108, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (275, 'Notorious', 'Action', 'Brynne Manuello', to_date('13-08-2022', 'dd-mm-yyyy'), 147, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (276, 'Amadeus', 'Fantasy', 'Harman Crate', to_date('22-11-2005', 'dd-mm-yyyy'), 122, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (277, 'Deadpool', 'Sport', 'Erica Langley', to_date('21-10-2022', 'dd-mm-yyyy'), 175, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (278, 'Arrival', 'Documentary', 'Niall Mustard', to_date('23-09-2007', 'dd-mm-yyyy'), 127, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (279, 'Clueless', 'Biography', 'Clywd Finlaison', to_date('28-02-2016', 'dd-mm-yyyy'), 119, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (280, 'Kill Bill', 'Drama', 'Fanchette Brothers', to_date('13-03-2015', 'dd-mm-yyyy'), 83, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (281, 'Gigi', 'Family', 'Ellene Drinkel', to_date('13-09-2005', 'dd-mm-yyyy'), 180, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (282, 'Cinderella', 'Mystery', 'Merralee Wrench', to_date('27-09-2009', 'dd-mm-yyyy'), 63, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (283, 'Rango', 'Crime', 'Kenon Paulitschke', to_date('01-11-2007', 'dd-mm-yyyy'), 79, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (284, 'Moonlight', 'War', 'Giralda Conachie', to_date('28-02-2009', 'dd-mm-yyyy'), 85, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (285, 'Spartacus', 'Documentary', 'Gwendolen Marians', to_date('31-12-2004', 'dd-mm-yyyy'), 113, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (286, 'Hugo', 'Mystery', 'Alexine Mowday', to_date('10-07-2009', 'dd-mm-yyyy'), 149, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (287, 'Trumbo', 'Drama', 'Nonah Hiscoke', to_date('24-12-2013', 'dd-mm-yyyy'), 134, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (288, 'Rio', 'Horror', 'Emogene Hadgraft', to_date('12-02-2006', 'dd-mm-yyyy'), 98, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (289, 'District 9', 'Horror', 'Seka Allbones', to_date('05-11-2011', 'dd-mm-yyyy'), 180, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (290, 'Split', 'History', 'Maryanna Streader', to_date('12-09-2003', 'dd-mm-yyyy'), 109, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (291, 'Airplane', 'Sci-Fi', 'Zara Kiljan', to_date('14-11-2018', 'dd-mm-yyyy'), 82, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (292, 'Boyhood', 'Action', 'Alley Mark', to_date('09-12-2022', 'dd-mm-yyyy'), 82, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (293, 'Risen', 'Sci-Fi', 'Trumaine Yanov', to_date('02-06-2014', 'dd-mm-yyyy'), 119, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (294, 'Coraline', 'Adventure', 'Enrichetta Conlon', to_date('28-06-2009', 'dd-mm-yyyy'), 96, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (295, 'Notebook', 'Comedy', 'Dredi Cansdell', to_date('02-06-2012', 'dd-mm-yyyy'), 63, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (296, 'Cop Land', 'Biography', 'Tully Torn', to_date('19-11-2022', 'dd-mm-yyyy'), 139, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (297, 'Boyhood', 'Crime', 'Barde Eeles', to_date('28-08-2017', 'dd-mm-yyyy'), 162, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (298, 'Contact', 'Drama', 'Jennine Bottlestone', to_date('22-12-2017', 'dd-mm-yyyy'), 156, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (299, 'Twister', 'Thriller', 'Eddie Lince', to_date('09-01-2015', 'dd-mm-yyyy'), 108, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (300, 'Split', 'Comedy', 'Rafaelita Drummond', to_date('18-05-2016', 'dd-mm-yyyy'), 147, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (301, 'Capote', 'Mystery', 'Staci Abdee', to_date('06-04-2014', 'dd-mm-yyyy'), 160, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (302, 'Goonies', 'War', 'Tally Deeney', to_date('27-09-2019', 'dd-mm-yyyy'), 70, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (303, 'Rudy', 'Horror', 'Latashia Romi', to_date('15-08-2010', 'dd-mm-yyyy'), 104, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (304, 'Sideways', 'Thriller', 'Pasquale Barstowk', to_date('11-01-2016', 'dd-mm-yyyy'), 143, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (305, 'Scream', 'War', 'Dorelia Millmoe', to_date('26-09-2014', 'dd-mm-yyyy'), 135, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (306, 'Avatar', 'Action', 'Lek Darrigone', to_date('15-06-2018', 'dd-mm-yyyy'), 99, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (307, 'Memento', 'Animation', 'Giusto Normington', to_date('12-08-2012', 'dd-mm-yyyy'), 154, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (308, 'Platoon', 'Musical', 'Dinny Wichard', to_date('10-06-2003', 'dd-mm-yyyy'), 77, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (309, 'Hancock', 'Sci-Fi', 'Eugine Skynner', to_date('02-02-2006', 'dd-mm-yyyy'), 110, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (310, 'Gandhi', 'Sport', 'Frasco Milch', to_date('27-03-2006', 'dd-mm-yyyy'), 108, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (311, 'Moana', 'Sci-Fi', 'Anita Westbrook', to_date('13-11-2006', 'dd-mm-yyyy'), 151, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (312, 'Hugo', 'Fantasy', 'Dell Skipworth', to_date('09-10-2003', 'dd-mm-yyyy'), 113, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (313, 'Twister', 'History', 'Lauralee Saltern', to_date('01-04-2002', 'dd-mm-yyyy'), 176, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (314, 'Ted', 'History', 'Fleming De Lorenzo', to_date('20-09-2005', 'dd-mm-yyyy'), 156, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (315, 'Avatar', 'Drama', 'Winfield Abrashkov', to_date('14-02-2004', 'dd-mm-yyyy'), 166, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (316, 'Patton', 'Musical', 'Dael Lockyear', to_date('26-10-2015', 'dd-mm-yyyy'), 129, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (317, 'Frida', 'Drama', 'Buddy Beadell', to_date('16-08-2016', 'dd-mm-yyyy'), 84, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (318, 'Grease', 'Crime', 'Jewel Southey', to_date('06-11-2023', 'dd-mm-yyyy'), 122, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (319, 'Capote', 'Sport', 'Jacenta Clendennen', to_date('20-03-2022', 'dd-mm-yyyy'), 103, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (320, 'Doubt', 'Drama', 'Dione Piddlesden', to_date('29-05-2023', 'dd-mm-yyyy'), 68, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (321, 'Gravity', 'Biography', 'Hal Trevillion', to_date('21-08-2021', 'dd-mm-yyyy'), 63, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (322, 'Black Swan', 'Mystery', 'Farah Beaford', to_date('14-02-2007', 'dd-mm-yyyy'), 160, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (323, 'Unforgiven', 'Musical', 'Mirabelle Paver', to_date('20-04-2022', 'dd-mm-yyyy'), 89, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (324, 'Crash', 'Musical', 'Clarice Batman', to_date('07-11-2014', 'dd-mm-yyyy'), 75, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (325, 'Witness', 'Family', 'Lodovico Franseco', to_date('22-05-2000', 'dd-mm-yyyy'), 166, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (326, 'Platoon', 'Documentary', 'Osmund Springer', to_date('31-08-2014', 'dd-mm-yyyy'), 171, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (327, 'Cowboys', 'Horror', 'Wilfrid Rizzardini', to_date('24-07-2016', 'dd-mm-yyyy'), 102, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (328, 'Star Trek', 'Documentary', 'Colleen Goulstone', to_date('13-06-2001', 'dd-mm-yyyy'), 75, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (329, 'Twister', 'Sport', 'Demott Hebson', to_date('19-03-2022', 'dd-mm-yyyy'), 118, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (330, 'Tombstone', 'Thriller', 'Norry Rollings', to_date('24-11-2016', 'dd-mm-yyyy'), 110, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (331, 'Speed', 'Adventure', 'Ingrim Adds', to_date('23-01-2018', 'dd-mm-yyyy'), 98, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (332, 'Thor', 'Family', 'Blanche Jaques', to_date('02-06-2016', 'dd-mm-yyyy'), 124, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (333, 'Rango', 'History', 'Clayson MacCorkell', to_date('28-05-2004', 'dd-mm-yyyy'), 160, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (334, 'Arrival', 'Sci-Fi', 'Dion McCumskay', to_date('08-01-2015', 'dd-mm-yyyy'), 126, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (335, 'Skyfall', 'Animation', 'Maxwell Syder', to_date('04-02-2024', 'dd-mm-yyyy'), 110, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (336, 'Holes', 'Documentary', 'Annmaria Bromidge', to_date('15-09-2011', 'dd-mm-yyyy'), 175, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (337, 'Chocolat', 'Animation', 'Reiko Palluschek', to_date('03-12-2017', 'dd-mm-yyyy'), 85, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (338, 'Flubber', 'Mystery', 'Shawn Dougherty', to_date('05-09-2023', 'dd-mm-yyyy'), 136, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (339, 'Split', 'Musical', 'Nona Benneton', to_date('08-10-2000', 'dd-mm-yyyy'), 72, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (340, 'Gladiator', 'Action', 'Kizzie Dulieu', to_date('30-01-2024', 'dd-mm-yyyy'), 142, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (341, 'Casino', 'Thriller', 'Shawn Williscroft', to_date('12-01-2011', 'dd-mm-yyyy'), 139, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (342, 'X-', 'Musical', 'Chris Elvy', to_date('20-02-2024', 'dd-mm-yyyy'), 79, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (343, 'Jumanji', 'Crime', 'Noll Mannix', to_date('15-02-2013', 'dd-mm-yyyy'), 139, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (344, 'Shutter', 'Crime', 'Theda Sarchwell', to_date('02-09-2014', 'dd-mm-yyyy'), 67, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (345, 'Giant', 'Documentary', 'Marissa Picot', to_date('22-02-2013', 'dd-mm-yyyy'), 73, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (346, 'Star Trek', 'Sport', 'Leanor Woodcroft', to_date('02-11-2005', 'dd-mm-yyyy'), 156, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (347, 'Amelie', 'Thriller', 'Hunt Ashbey', to_date('27-08-2018', 'dd-mm-yyyy'), 138, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (348, 'Witness', 'Sport', 'Lief Ronisch', to_date('07-12-2000', 'dd-mm-yyyy'), 80, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (349, 'Crash', 'Biography', 'Neil Gilliam', to_date('17-12-2001', 'dd-mm-yyyy'), 177, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (350, 'Crash', 'Action', 'Hedvig Mars', to_date('05-09-2002', 'dd-mm-yyyy'), 134, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (351, 'Kill Bill', 'Crime', 'Leesa Dalwood', to_date('23-07-2005', 'dd-mm-yyyy'), 135, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (352, 'Ratatouille', 'History', 'Carlotta Winstone', to_date('02-06-2010', 'dd-mm-yyyy'), 67, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (353, 'Trumbo', 'History', 'Salome Gredden', to_date('01-06-2009', 'dd-mm-yyyy'), 178, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (354, 'Speed', 'Mystery', 'Levey Paudin', to_date('13-03-2012', 'dd-mm-yyyy'), 129, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (355, 'Stargate', 'History', 'Ruthy Rosenstein', to_date('08-11-2010', 'dd-mm-yyyy'), 146, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (356, 'Sideways', 'Animation', 'Bert Slowan', to_date('26-09-2009', 'dd-mm-yyyy'), 72, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (357, 'Airplane', 'War', 'Connie Withull', to_date('17-02-2015', 'dd-mm-yyyy'), 122, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (358, 'Clerks', 'History', 'Fawnia Heaysman', to_date('31-07-2004', 'dd-mm-yyyy'), 99, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (359, 'Ted', 'Family', 'Luigi Bossons', to_date('18-10-2019', 'dd-mm-yyyy'), 130, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (360, 'Fences', 'Horror', 'Darlene McKinty', to_date('04-09-2007', 'dd-mm-yyyy'), 104, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (361, 'Flubber', 'Musical', 'Errick Aulton', to_date('02-07-2001', 'dd-mm-yyyy'), 145, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (362, 'Bolt', 'Crime', 'Toby Humblestone', to_date('13-10-2015', 'dd-mm-yyyy'), 92, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (363, 'Twister', 'Horror', 'Evangelina Saw', to_date('21-10-2009', 'dd-mm-yyyy'), 159, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (364, 'Tombstone', 'Crime', 'Doralynne Gannaway', to_date('12-11-2001', 'dd-mm-yyyy'), 150, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (365, 'Aliens', 'Mystery', 'Abbey Robel', to_date('25-12-2016', 'dd-mm-yyyy'), 87, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (366, 'Gravity', 'Animation', 'Natka Tysack', to_date('04-03-2004', 'dd-mm-yyyy'), 127, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (367, 'Iron Man', 'Horror', 'Gregorio Hirsthouse', to_date('05-03-2015', 'dd-mm-yyyy'), 161, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (368, 'Signs', 'Mystery', 'Seymour Jatczak', to_date('28-05-2003', 'dd-mm-yyyy'), 77, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (369, 'Capote', 'Mystery', 'Greta Bras', to_date('08-10-2014', 'dd-mm-yyyy'), 67, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (370, 'Whiplash', 'Documentary', 'Cristine Gagan', to_date('08-10-2018', 'dd-mm-yyyy'), 112, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (371, 'Casino', 'Sport', 'Cassy Killingworth', to_date('22-02-2010', 'dd-mm-yyyy'), 129, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (372, 'Logan', 'Biography', 'Candy Le Gassick', to_date('27-01-2023', 'dd-mm-yyyy'), 131, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (373, 'Aliens', 'Family', 'Mattias Braybrook', to_date('15-10-2023', 'dd-mm-yyyy'), 147, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (374, 'Lincoln', 'Biography', 'Ewell Korb', to_date('31-05-2019', 'dd-mm-yyyy'), 134, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (375, 'Spartacus', 'Fantasy', 'Roselin Gurnay', to_date('26-10-2020', 'dd-mm-yyyy'), 135, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (376, 'Sideways', 'History', 'Evania Curton', to_date('18-03-2016', 'dd-mm-yyyy'), 159, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (377, 'Singles', 'Thriller', 'Elnar Foulis', to_date('25-02-2011', 'dd-mm-yyyy'), 105, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (378, 'Mad Max', 'Sci-Fi', 'Albertina Shinfield', to_date('23-06-2022', 'dd-mm-yyyy'), 101, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (379, 'Shrek', 'History', 'Goldina Lovie', to_date('21-09-2006', 'dd-mm-yyyy'), 131, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (380, 'Hancock', 'Mystery', 'Laurene Cristofolo', to_date('30-10-2006', 'dd-mm-yyyy'), 100, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (381, 'Selma', 'Documentary', 'Clemmie Verni', to_date('06-01-2005', 'dd-mm-yyyy'), 150, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (382, 'Gattaca', 'Action', 'Roobbie Possek', to_date('02-08-2016', 'dd-mm-yyyy'), 133, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (383, 'Ray', 'Family', 'Goober Withull', to_date('05-09-2003', 'dd-mm-yyyy'), 95, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (384, 'Notorious', 'Sport', 'Wendy Langthorne', to_date('18-02-2019', 'dd-mm-yyyy'), 171, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (385, 'True Lies', 'Action', 'Dorise Rhead', to_date('30-05-2001', 'dd-mm-yyyy'), 81, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (386, 'Speed', 'Western', 'Hartwell Ertelt', to_date('25-12-2010', 'dd-mm-yyyy'), 83, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (387, 'Sideways', 'Sport', 'Grant Suttle', to_date('27-07-2010', 'dd-mm-yyyy'), 103, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (388, 'Unforgiven', 'History', 'Lorne Springate', to_date('15-06-2019', 'dd-mm-yyyy'), 176, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (389, 'Dumbo', 'Drama', 'Edlin Samper', to_date('28-09-2014', 'dd-mm-yyyy'), 164, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (390, 'Giant', 'History', 'Abran Sabbin', to_date('21-10-2001', 'dd-mm-yyyy'), 117, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (391, 'Shutter', 'Biography', 'Buffy Kolakovic', to_date('18-06-2020', 'dd-mm-yyyy'), 94, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (392, 'Up', 'Animation', 'Jeannine Garfoot', to_date('04-08-2020', 'dd-mm-yyyy'), 156, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (393, 'Frozen', 'Action', 'Braden Tivenan', to_date('17-07-2008', 'dd-mm-yyyy'), 88, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (394, 'Hancock', 'Animation', 'Rois Bucknall', to_date('08-10-2013', 'dd-mm-yyyy'), 85, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (395, 'Looper', 'Mystery', 'Reta Skelhorn', to_date('06-10-2023', 'dd-mm-yyyy'), 134, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (396, 'Moana', 'Thriller', 'Dory Wilstead', to_date('20-05-2010', 'dd-mm-yyyy'), 150, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (397, 'Watchmen', 'War', 'Thorsten Pillman', to_date('06-03-2003', 'dd-mm-yyyy'), 82, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (398, 'Coraline', 'Biograp', 'Ynes O'' Mullan', to_date('08-11-2016', 'dd-mm-yyyy'), 171, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (399, 'Brave', 'Biography', 'Webster Ellse', to_date('05-10-2020', 'dd-mm-yyyy'), 143, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (400, 'Lincoln', 'Action', 'Ebenezer Tapner', to_date('19-01-2016', 'dd-mm-yyyy'), 73, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (401, 'Matilda', 'Thriller', 'Kris Colter', to_date('13-03-2002', 'dd-mm-yyyy'), 124, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (402, 'Clueless', 'Documentary', 'Teresa Mair', to_date('15-06-2001', 'dd-mm-yyyy'), 72, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (403, 'Superbad', 'Thriller', 'Leslie O''Hear', to_date('02-04-2022', 'dd-mm-yyyy'), 76, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (404, 'Gattaca', 'Western', 'Nettie Whipple', to_date('30-05-2011', 'dd-mm-yyyy'), 176, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (405, 'Casino', 'Mystery', 'Hamnet McKenzie', to_date('29-12-2006', 'dd-mm-yyyy'), 128, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (406, 'Trumbo', 'Horror', 'Maure Olijve', to_date('09-02-2006', 'dd-mm-yyyy'), 95, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (407, 'Xanadu', 'Fantasy', 'Dorie Joskovitch', to_date('13-06-2006', 'dd-mm-yyyy'), 144, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (408, 'Bambi', 'Mystery', 'Mareah Fussell', to_date('22-02-2005', 'dd-mm-yyyy'), 80, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (409, 'Black Swan', 'Sci-Fi', 'Georgianne Leiden', to_date('25-05-2001', 'dd-mm-yyyy'), 66, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (410, 'Sin City', 'Romance', 'Ray O''Hallagan', to_date('17-10-2008', 'dd-mm-yyyy'), 176, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (411, 'Sideways', 'History', 'Ana Pittam', to_date('10-07-2003', 'dd-mm-yyyy'), 99, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (412, 'Grease', 'Sci-Fi', 'Aline Huck', to_date('06-04-2022', 'dd-mm-yyyy'), 87, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (413, 'Iron Man', 'Drama', 'Baxie Bellson', to_date('30-01-2017', 'dd-mm-yyyy'), 116, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (414, 'Jumper', 'Horror', 'Cassius Creelman', to_date('19-03-2018', 'dd-mm-yyyy'), 150, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (415, 'Grease', 'Mystery', 'Genevra Dietmar', to_date('20-07-2004', 'dd-mm-yyyy'), 135, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (416, 'Manhunter', 'War', 'Curry Longmuir', to_date('30-08-2013', 'dd-mm-yyyy'), 99, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (417, 'Black Swan', 'Documentary', 'Brittne Emilien', to_date('15-07-2016', 'dd-mm-yyyy'), 114, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (418, 'Fury', 'Biography', 'Augustus Dabs', to_date('28-06-2018', 'dd-mm-yyyy'), 85, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (419, 'Aliens', 'Romance', 'Effie Van Der Weedenburg', to_date('28-03-2009', 'dd-mm-yyyy'), 67, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (420, 'Arrival', 'History', 'Lanette Beeho', to_date('05-01-2002', 'dd-mm-yyyy'), 67, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (421, 'Contact', 'Animation', 'Amby Cruddace', to_date('22-10-2017', 'dd-mm-yyyy'), 157, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (422, 'Big Fish', 'Crime', 'Kamilah Izkovici', to_date('26-03-2013', 'dd-mm-yyyy'), 175, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (423, 'Ted', 'Comedy', 'Corrie Atkyns', to_date('06-03-2002', 'dd-mm-yyyy'), 78, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (424, 'Aliens', 'Family', 'Richy Matfin', to_date('26-06-2000', 'dd-mm-yyyy'), 143, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (425, 'Lincoln', 'Mystery', 'Stephine Bassham', to_date('18-05-2023', 'dd-mm-yyyy'), 124, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (426, 'Rushmore', 'Action', 'Loy Senechell', to_date('12-05-2009', 'dd-mm-yyyy'), 136, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (427, 'Up', 'War', 'Ellette Sidey', to_date('03-02-2022', 'dd-mm-yyyy'), 80, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (428, 'Moana', 'Thriller', 'Joelynn Elster', to_date('14-12-2015', 'dd-mm-yyyy'), 140, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (429, 'Brave', 'Musical', 'Meredeth Szymanek', to_date('04-10-2004', 'dd-mm-yyyy'), 139, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (430, 'Coco', 'Action', 'Florrie Flury', to_date('21-06-2022', 'dd-mm-yyyy'), 159, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (431, 'Signs', 'Animation', 'Natalie Hoodspeth', to_date('01-01-2019', 'dd-mm-yyyy'), 140, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (432, 'Memento', 'War', 'Sacha Henzley', to_date('22-05-2010', 'dd-mm-yyyy'), 101, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (433, 'Godzilla', 'Comedy', 'Emalia Scopyn', to_date('30-01-2009', 'dd-mm-yyyy'), 156, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (434, 'Elf', 'Action', 'Odessa Friedlos', to_date('22-06-2001', 'dd-mm-yyyy'), 165, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (435, 'Unforgiven', 'Horror', 'Monty Lehrmann', to_date('18-05-2004', 'dd-mm-yyyy'), 71, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (436, 'Rudy', 'Thriller', 'Sile Gimblet', to_date('22-11-2021', 'dd-mm-yyyy'), 180, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (437, 'Deadpool', 'Western', 'Agatha Huckabe', to_date('07-02-2007', 'dd-mm-yyyy'), 135, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (438, 'Serenity', 'Action', 'Ari Cotterel', to_date('20-07-2002', 'dd-mm-yyyy'), 161, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (439, 'Tombstone', 'Documentary', 'Pansie Rosencwaig', to_date('04-10-2010', 'dd-mm-yyyy'), 67, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (440, 'Dune', 'Romance', 'Catie MacRury', to_date('18-05-2012', 'dd-mm-yyyy'), 158, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (441, 'Boyhood', 'Family', 'Ashlin Daish', to_date('20-05-2003', 'dd-mm-yyyy'), 161, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (442, 'Xanadu', 'Sci-Fi', 'Armando Carass', to_date('12-04-2019', 'dd-mm-yyyy'), 179, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (443, 'Godzilla', 'Biography', 'Adriana Windle', to_date('02-05-2010', 'dd-mm-yyyy'), 178, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (444, 'Unforgiven', 'History', 'Lauree Pilgrim', to_date('11-08-2005', 'dd-mm-yyyy'), 107, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (445, 'Rudy', 'Romance', 'Kilian Giacomazzo', to_date('15-06-2004', 'dd-mm-yyyy'), 115, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (446, 'Spartacus', 'Western', 'Lyon Cleyburn', to_date('04-10-2015', 'dd-mm-yyyy'), 60, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (447, 'Gandhi', 'Musical', 'Sibylle MacFadyen', to_date('07-07-2009', 'dd-mm-yyyy'), 164, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (448, 'Fargo', 'Horror', 'Grethel Darter', to_date('03-03-2002', 'dd-mm-yyyy'), 129, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (449, 'Goonies', 'Western', 'Gina Hollyman', to_date('03-02-2011', 'dd-mm-yyyy'), 96, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (450, 'Fences', 'Western', 'Arleyne Hedgecock', to_date('11-12-2014', 'dd-mm-yyyy'), 70, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (451, 'Titanic', 'Fantasy', 'Vernor Whyke', to_date('15-06-2023', 'dd-mm-yyyy'), 171, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (452, 'Amelie', 'Sci-Fi', 'Laure Noye', to_date('04-03-2017', 'dd-mm-yyyy'), 122, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (453, 'Clueless', 'Sport', 'Penn Hewlings', to_date('12-10-2003', 'dd-mm-yyyy'), 107, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (454, 'Gattaca', 'Comedy', 'Daron Cash', to_date('11-11-2021', 'dd-mm-yyyy'), 144, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (455, 'Gandhi', 'Biography', 'Daniella Showler', to_date('27-08-2006', 'dd-mm-yyyy'), 128, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (456, 'Kill Bill', 'Western', 'Abbi Casa', to_date('04-05-2004', 'dd-mm-yyyy'), 137, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (457, 'Wild', 'Sci-Fi', 'Benni Curley', to_date('17-11-2013', 'dd-mm-yyyy'), 121, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (458, 'Stargate', 'Crime', 'Elissa Francillo', to_date('06-09-2002', 'dd-mm-yyyy'), 139, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (459, 'Gladiator', 'Thriller', 'Filip Martell', to_date('10-06-2010', 'dd-mm-yyyy'), 129, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (460, 'Doubt', 'Family', 'Ber MacGillavery', to_date('04-03-2021', 'dd-mm-yyyy'), 66, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (461, 'Amadeus', 'War', 'Salaidh Gever', to_date('28-01-2005', 'dd-mm-yyyy'), 94, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (462, 'Coco', 'Mystery', 'Cordelie Girard', to_date('27-08-2019', 'dd-mm-yyyy'), 128, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (463, 'Twister', 'Musical', 'Isac Bickerstaff', to_date('31-08-2006', 'dd-mm-yyyy'), 179, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (464, 'Frida', 'War', 'Hirsch Dubble', to_date('03-10-2000', 'dd-mm-yyyy'), 135, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (465, 'Creed', 'Horror', 'Eadie McKern', to_date('20-12-2010', 'dd-mm-yyyy'), 171, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (466, 'Split', 'Sport', 'Mikael Libermore', to_date('09-01-2017', 'dd-mm-yyyy'), 65, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (467, 'Unbroken', 'War', 'Jayson Winser', to_date('14-10-2009', 'dd-mm-yyyy'), 172, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (468, 'Memento', 'Romance', 'Constantino Scandred', to_date('22-09-2022', 'dd-mm-yyyy'), 114, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (469, 'Capote', 'Western', 'Titos Fairbrass', to_date('15-06-2001', 'dd-mm-yyyy'), 142, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (470, 'Twister', 'Family', 'Eryn Gouch', to_date('19-12-2010', 'dd-mm-yyyy'), 176, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (471, 'Clerks', 'Western', 'Maddie Wisedale', to_date('12-11-2008', 'dd-mm-yyyy'), 163, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (472, 'Ben-Hur', 'Comedy', 'Esteban Junifer', to_date('08-03-2006', 'dd-mm-yyyy'), 95, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (473, 'Manhunter', 'War', 'Bernadina Shoppee', to_date('14-01-2022', 'dd-mm-yyyy'), 126, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (474, 'Logan', 'Crime', 'Rafaela Trevena', to_date('08-12-2007', 'dd-mm-yyyy'), 164, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (475, 'Serenity', 'Thriller', 'Flin Murphey', to_date('02-05-2017', 'dd-mm-yyyy'), 137, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (476, 'Hugo', 'Sci-Fi', 'Robbi Clampett', to_date('27-01-2009', 'dd-mm-yyyy'), 90, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (477, 'Frozen', 'Thriller', 'Alexandre Schlagman', to_date('15-05-2016', 'dd-mm-yyyy'), 176, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (478, 'Birdman', 'Drama', 'Delmor Rosie', to_date('07-03-2006', 'dd-mm-yyyy'), 132, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (479, 'Grease', 'Sci-Fi', 'Trix Palfery', to_date('22-04-2006', 'dd-mm-yyyy'), 119, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (480, 'Gattaca', 'Crime', 'Lotty Minshall', to_date('23-03-2013', 'dd-mm-yyyy'), 158, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (481, 'Trumbo', 'Sci-Fi', 'Saudra Duce', to_date('19-05-2020', 'dd-mm-yyyy'), 85, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (482, 'The Mask', 'Western', 'Alano Purdon', to_date('16-01-2024', 'dd-mm-yyyy'), 145, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (483, 'Titanic', 'Sport', 'Zsa zsa Southan', to_date('27-03-2015', 'dd-mm-yyyy'), 119, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (484, 'Labyrinth', 'Documentary', 'Ange Midgely', to_date('03-01-2010', 'dd-mm-yyyy'), 146, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (485, 'Casino', 'Documentary', 'Monique Paff', to_date('28-05-2006', 'dd-mm-yyyy'), 64, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (486, 'Giant', 'Biography', 'Yettie Partridge', to_date('06-11-2003', 'dd-mm-yyyy'), 150, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (487, 'Doubt', 'Documentary', 'Kinnie Reede', to_date('23-08-2012', 'dd-mm-yyyy'), 153, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (488, 'Grease', 'Sci-Fi', 'Ludwig Valentelli', to_date('26-03-2006', 'dd-mm-yyyy'), 135, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (489, 'Crash', 'History', 'Griff Welling', to_date('14-07-2006', 'dd-mm-yyyy'), 143, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (490, 'Serenity', 'Animation', 'Spenser Bartels-Ellis', to_date('24-10-2018', 'dd-mm-yyyy'), 155, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (491, 'Elf', 'Drama', 'Vivienne Grimditch', to_date('13-11-2009', 'dd-mm-yyyy'), 117, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (492, 'Scarface', 'Fantasy', 'Cobby Tossell', to_date('27-07-2005', 'dd-mm-yyyy'), 128, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (493, 'Clerks', 'Crime', 'Quinlan Pargent', to_date('13-05-2011', 'dd-mm-yyyy'), 116, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (494, 'Rocky II', 'Adventure', 'Lena Metheringham', to_date('27-02-2003', 'dd-mm-yyyy'), 79, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (495, 'Hancock', 'Thriller', 'Morton Worts', to_date('19-04-2018', 'dd-mm-yyyy'), 63, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (496, 'Zoolander', 'Action', 'Aretha Crosthwaite', to_date('08-04-2022', 'dd-mm-yyyy'), 105, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (497, 'Amadeus', 'Western', 'Wheeler Dougher', to_date('04-03-2017', 'dd-mm-yyyy'), 100, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (498, 'Ant-Man', 'Documentary', 'Essie Decroix', to_date('30-07-2001', 'dd-mm-yyyy'), 118, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (499, 'Holes', 'Horror', 'Ephrem Whitebread', to_date('07-10-2002', 'dd-mm-yyyy'), 87, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values (500, 'Spartacus', 'Animation', 'Brunhilde Gyrgorcewicx', to_date('09-05-2012', 'dd-mm-yyyy'), 166, 2);
