insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('202', 'Goonies', 'Sci-Fi', 'Maressa Summersett', to_date('26-02-2011', 'dd-mm-yyyy'), 179, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('956', 'Witness', 'Sport', 'Fabe Dallaghan', to_date('20-03-2017', 'dd-mm-yyyy'), 172, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('216', 'Witness', 'Drama', 'Stormi Gergher', to_date('24-07-2022', 'dd-mm-yyyy'), 133, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('482', 'Monsters', 'Romance', 'Son Drugan', to_date('20-03-2001', 'dd-mm-yyyy'), 64, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('623', 'Capote', 'Romance', 'Emmalee Manueau', to_date('17-03-2022', 'dd-mm-yyyy'), 66, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('432', 'Ratatouille', 'Sci-Fi', 'Tyne Falkous', to_date('05-03-2001', 'dd-mm-yyyy'), 108, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('464', 'Rocky', 'War', 'Sadie Raiker', to_date('25-09-2003', 'dd-mm-yyyy'), 62, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('202', 'Matilda', 'Sci-Fi', 'Hermie Domaschke', to_date('12-06-2007', 'dd-mm-yyyy'), 174, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('479', 'Spartacus', 'Documentary', 'Robbi Naper', to_date('05-02-2008', 'dd-mm-yyyy'), 142, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('113', 'Hancock', 'Animation', 'Consolata Starkie', to_date('05-07-2013', 'dd-mm-yyyy'), 126, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('418', 'Alien', 'Biography', 'Vidovic Howgill', to_date('05-12-2006', 'dd-mm-yyyy'), 138, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('435', 'Big Fish', 'Action', 'Bennie Fabbri', to_date('04-03-2018', 'dd-mm-yyyy'), 178, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('492', 'Big Fish', 'Animation', 'Jesse Cornelisse', to_date('27-08-2014', 'dd-mm-yyyy'), 152, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('255', 'Creed', 'Mystery', 'Roselle Loggie', to_date('21-08-2014', 'dd-mm-yyyy'), 102, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('929', 'Creed', 'Western', 'Barton Moncarr', to_date('25-09-2001', 'dd-mm-yyyy'), 121, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('407', 'Sideways', 'Adventure', 'Renelle Gavey', to_date('28-07-2007', 'dd-mm-yyyy'), 65, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('447', 'Fury', 'Musical', 'Shayna Couldwell', to_date('14-10-2000', 'dd-mm-yyyy'), 180, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('116', 'Crash', 'Biography', 'Lily Tite', to_date('25-07-2011', 'dd-mm-yyyy'), 119, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('886', 'Iron Man', 'Adventure', 'Cornell Upwood', to_date('12-12-2009', 'dd-mm-yyyy'), 100, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('967', 'Brave', 'Animation', 'Drusi Pardal', to_date('27-10-2017', 'dd-mm-yyyy'), 146, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('890', 'Witness', 'Thriller', 'Jayme Casaletto', to_date('08-06-2007', 'dd-mm-yyyy'), 110, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('460', 'Chappie', 'Mystery', 'Tomas Janicijevic', to_date('25-01-2013', 'dd-mm-yyyy'), 154, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('351', 'Hancock', 'Drama', 'Fianna Oppery', to_date('02-03-2013', 'dd-mm-yyyy'), 74, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('384', 'Risen', 'Adventure', 'Robby Garratt', to_date('22-04-2024', 'dd-mm-yyyy'), 119, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('231', 'Rocky II', 'Comedy', 'Linette Faughnan', to_date('24-06-2018', 'dd-mm-yyyy'), 176, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('888', 'Tombstone', 'Western', 'Robbin Stagg', to_date('03-02-2020', 'dd-mm-yyyy'), 98, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('571', 'Heat', 'Romance', 'Erasmus Penritt', to_date('18-02-2010', 'dd-mm-yyyy'), 65, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('261', 'Gladiator', 'Sport', 'Sherman Gabbitas', to_date('24-10-2014', 'dd-mm-yyyy'), 147, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('137', 'Memento', 'Documentary', 'Moira Bakewell', to_date('17-11-2003', 'dd-mm-yyyy'), 117, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('500', 'Saw', 'Fantasy', 'Roch Bastable', to_date('15-09-2016', 'dd-mm-yyyy'), 97, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('112', 'Star Trek', 'Documentary', 'Zaccaria Stranieri', to_date('27-01-2020', 'dd-mm-yyyy'), 120, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('624', 'Gattaca', 'Fantasy', 'Dasie Wormald', to_date('05-09-2010', 'dd-mm-yyyy'), 152, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('399', 'Notebook', 'Documentary', 'Torie Michieli', to_date('28-02-2011', 'dd-mm-yyyy'), 131, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('711', 'District 9', 'Adventure', 'Hasty Simpkin', to_date('07-09-2000', 'dd-mm-yyyy'), 111, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('201', 'Moana', 'Musical', 'Rolland Humblestone', to_date('11-05-2017', 'dd-mm-yyyy'), 175, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('954', 'Memento', 'Biograp', 'Brandais Le Moucheux', to_date('05-08-2021', 'dd-mm-yyyy'), 133, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('248', 'Gattaca', 'Horror', 'Staford Ferenczy', to_date('09-01-2024', 'dd-mm-yyyy'), 97, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('318', 'Spartacus', 'Mystery', 'Cristobal Raun', to_date('04-11-2003', 'dd-mm-yyyy'), 113, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('133', 'Witness', 'Musical', 'Mike Beeswing', to_date('20-11-2011', 'dd-mm-yyyy'), 113, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('771', 'Patton', 'History', 'Odette Tetther', to_date('31-05-2020', 'dd-mm-yyyy'), 85, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('383', 'Zodiac', 'Thriller', 'Nevsa Vittel', to_date('22-05-2017', 'dd-mm-yyyy'), 155, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('606', 'Sin City', 'History', 'Alfy Murrum', to_date('19-03-2003', 'dd-mm-yyyy'), 121, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('843', 'Risen', 'Western', 'Albina Hamblen', to_date('02-04-2015', 'dd-mm-yyyy'), 166, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('187', 'Speed', 'Horror', 'Tomas Nappin', to_date('18-07-2021', 'dd-mm-yyyy'), 147, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('805', 'Eraser', 'Action', 'Chelsae Piggens', to_date('02-09-2011', 'dd-mm-yyyy'), 114, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('291', 'Lincoln', 'Thriller', 'Georgeanna Bruckshaw', to_date('29-03-2010', 'dd-mm-yyyy'), 89, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('438', 'Gattaca', 'Fantasy', 'Elisabeth Slingsby', to_date('30-09-2017', 'dd-mm-yyyy'), 155, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('857', 'Notorious', 'Horror', 'Petunia Ahlin', to_date('11-11-2020', 'dd-mm-yyyy'), 134, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('281', 'Frozen', 'Western', 'Marna Hudson', to_date('29-05-2000', 'dd-mm-yyyy'), 65, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('415', 'The Mask', 'Sport', 'Farly Idel', to_date('20-09-2016', 'dd-mm-yyyy'), 143, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('754', 'Amadeus', 'Mystery', 'Maxy Maven', to_date('14-03-2009', 'dd-mm-yyyy'), 78, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('378', 'Psycho', 'History', 'Isabelle Gilchriest', to_date('12-08-2009', 'dd-mm-yyyy'), 172, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('367', 'Godzilla', 'Adventure', 'Baron Vacher', to_date('04-06-2023', 'dd-mm-yyyy'), 132, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('349', 'Brave', 'Action', 'Adolphe Reeder', to_date('15-04-2022', 'dd-mm-yyyy'), 80, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('448', 'Rudy', 'Fantasy', 'Eziechiele Heskey', to_date('28-01-2014', 'dd-mm-yyyy'), 180, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('364', 'Aliens', 'Horror', 'Vick Bean', to_date('17-09-2009', 'dd-mm-yyyy'), 156, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('311', 'Coraline', 'Action', 'Gary Kift', to_date('17-01-2008', 'dd-mm-yyyy'), 106, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('625', 'Avatar', 'Crime', 'Cly Worssam', to_date('21-02-2001', 'dd-mm-yyyy'), 121, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('895', 'Hugo', 'Biograp', 'Casey Piquard', to_date('31-01-2021', 'dd-mm-yyyy'), 108, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('454', 'Paprika', 'Western', 'Bunny Durdy', to_date('03-08-2000', 'dd-mm-yyyy'), 86, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('183', 'Saw', 'Action', 'Robena Younghusband', to_date('07-10-2020', 'dd-mm-yyyy'), 178, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('535', 'Ant-Man', 'Romance', 'Bell Vasentsov', to_date('11-04-2021', 'dd-mm-yyyy'), 151, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('928', 'Crash', 'Comedy', 'Jonathon Ginn', to_date('23-12-2002', 'dd-mm-yyyy'), 60, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('729', 'Mulan', 'Biography', 'Townie Cridlin', to_date('15-11-2000', 'dd-mm-yyyy'), 149, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('469', 'Twister', 'Mystery', 'Nikolaus Filshin', to_date('28-10-2011', 'dd-mm-yyyy'), 96, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('410', 'Holes', 'Musical', 'Chrissie Box', to_date('26-08-2010', 'dd-mm-yyyy'), 143, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('715', 'Witness', 'History', 'Gerick MacCook', to_date('31-01-2016', 'dd-mm-yyyy'), 141, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('788', 'Boyhood', 'Comedy', 'Windy Cochet', to_date('03-04-2021', 'dd-mm-yyyy'), 153, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('038', 'Rudy', 'Thriller', 'Claudine Yurmanovev', to_date('27-10-2015', 'dd-mm-yyyy'), 148, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('257', 'Speed', 'Thriller', 'Bridgette Vannacci', to_date('05-10-2013', 'dd-mm-yyyy'), 161, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('438', 'Memento', 'Thriller', 'Raynor Oaten', to_date('31-03-2005', 'dd-mm-yyyy'), 64, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('397', 'Hancock', 'Comedy', 'Shepard Edlington', to_date('29-07-2003', 'dd-mm-yyyy'), 149, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('612', 'Avatar', 'Romance', 'Karney Mosedale', to_date('19-09-2016', 'dd-mm-yyyy'), 67, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('991', 'X-', 'Action', 'Mac Calvie', to_date('17-02-2010', 'dd-mm-yyyy'), 176, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('111', 'Risen', 'Mystery', 'Maude Waistell', to_date('07-09-2004', 'dd-mm-yyyy'), 79, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('413', 'Cop Land', 'Sport', 'Christina Lipgens', to_date('06-06-2022', 'dd-mm-yyyy'), 144, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('846', 'Rango', 'Family', 'Ophelie Scay', to_date('22-03-2006', 'dd-mm-yyyy'), 92, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('119', 'Rent', 'History', 'Bay Arton', to_date('14-07-2021', 'dd-mm-yyyy'), 138, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('901', 'Ratatouille', 'Crime', 'Cherilynn Wortley', to_date('18-09-2001', 'dd-mm-yyyy'), 152, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('297', 'Shutter', 'History', 'Lorrayne Grumbridge', to_date('23-04-2018', 'dd-mm-yyyy'), 153, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('640', 'Boyhood', 'Western', 'Marylinda Northey', to_date('21-03-2008', 'dd-mm-yyyy'), 106, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('370', 'Goonies', 'Documentary', 'Lexine Bernli', to_date('27-08-2003', 'dd-mm-yyyy'), 63, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('717', 'Rudy', 'Fantasy', 'Marchall Cornejo', to_date('11-09-2007', 'dd-mm-yyyy'), 162, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('612', 'Tombstone', 'Western', 'Glenden Eldrett', to_date('21-04-2004', 'dd-mm-yyyy'), 73, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('372', 'X-', 'Musical', 'Ferd Trenholme', to_date('29-08-2016', 'dd-mm-yyyy'), 127, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('293', 'Hercules', 'Musical', 'Claudia Taaffe', to_date('11-03-2023', 'dd-mm-yyyy'), 104, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('526', 'Ant-Man', 'Thriller', 'Joseph Twort', to_date('01-10-2006', 'dd-mm-yyyy'), 88, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('068', 'Moana', 'Documentary', 'Leroy Kowalik', to_date('08-02-2017', 'dd-mm-yyyy'), 66, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('066', 'Fury', 'Fantasy', 'Caty Cantera', to_date('29-05-2015', 'dd-mm-yyyy'), 180, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('020', 'Big', 'Mystery', 'Fielding Blaylock', to_date('12-09-2017', 'dd-mm-yyyy'), 116, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('160', 'Hugo', 'Romance', 'Hollie Lakes', to_date('13-09-2016', 'dd-mm-yyyy'), 126, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('450', 'Speed', 'Adventure', 'Ivette Bufton', to_date('29-07-2016', 'dd-mm-yyyy'), 149, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('116', 'Big', 'Mystery', 'Fredek Jindrak', to_date('01-12-2010', 'dd-mm-yyyy'), 107, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('269', 'Witness', 'Animation', 'Lemmy Quickenden', to_date('22-07-2009', 'dd-mm-yyyy'), 128, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('942', 'Thor', 'Animation', 'Gradeigh Eberle', to_date('23-05-2005', 'dd-mm-yyyy'), 137, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('198', 'Hugo', 'War', 'Bab Raspel', to_date('21-06-2000', 'dd-mm-yyyy'), 147, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('982', 'Paprika', 'Comedy', 'Agretha Danes', to_date('24-11-2009', 'dd-mm-yyyy'), 143, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('341', 'Memento', 'Sport', 'Agnes Parlatt', to_date('15-10-2013', 'dd-mm-yyyy'), 100, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('806', 'Twister', 'Romance', 'Conn Crutchley', to_date('04-07-2020', 'dd-mm-yyyy'), 142, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('899', 'Tombstone', 'History', 'Abdul Turvie', to_date('14-11-2005', 'dd-mm-yyyy'), 151, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('859', 'Sideways', 'Adventure', 'Lanette Donaho', to_date('12-01-2019', 'dd-mm-yyyy'), 89, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('448', 'Frozen', 'Biography', 'Frasquito Hanne', to_date('22-10-2010', 'dd-mm-yyyy'), 60, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('868', 'Airplane', 'Horror', 'Cami Tuckley', to_date('27-07-2006', 'dd-mm-yyyy'), 152, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('747', 'Twister', 'Comedy', 'Dasi Morant', to_date('24-05-2014', 'dd-mm-yyyy'), 62, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('956', 'Creed', 'Sci-Fi', 'Piper Foulds', to_date('02-01-2009', 'dd-mm-yyyy'), 127, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('439', 'Shutter', 'History', 'Maurine Dablin', to_date('19-11-2003', 'dd-mm-yyyy'), 149, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('220', 'Ratatouille', 'Sport', 'Anet Mulliner', to_date('25-06-2023', 'dd-mm-yyyy'), 172, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('665', 'Iron Man', 'Drama', 'Hedda Coule', to_date('11-10-2017', 'dd-mm-yyyy'), 96, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('929', 'Moana', 'Crime', 'Gaston Lowmass', to_date('27-12-2013', 'dd-mm-yyyy'), 89, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('519', 'Bambi', 'Biography', 'Albrecht Grevel', to_date('26-08-2015', 'dd-mm-yyyy'), 170, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('496', 'Twister', 'Adventure', 'Pet Hecks', to_date('13-06-2012', 'dd-mm-yyyy'), 102, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('046', 'Chappie', 'Animation', 'Ertha Pittoli', to_date('09-08-2016', 'dd-mm-yyyy'), 123, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('130', 'Poltergeist', 'Mystery', 'Thia Orrick', to_date('20-11-2011', 'dd-mm-yyyy'), 126, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('322', 'Heat', 'Musical', 'Tommy Chantrell', to_date('07-11-2014', 'dd-mm-yyyy'), 149, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('315', 'Moana', 'Mystery', 'Celene Kinman', to_date('21-07-2023', 'dd-mm-yyyy'), 145, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('891', 'Unforgiven', 'Mystery', 'Kathe Elson', to_date('16-06-2004', 'dd-mm-yyyy'), 103, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('159', 'Hancock', 'War', 'Hersh Polding', to_date('06-03-2022', 'dd-mm-yyyy'), 89, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('502', 'Coraline', 'Western', 'Mallissa Banbrook', to_date('14-04-2013', 'dd-mm-yyyy'), 77, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('407', 'Ali', 'History', 'Mitzi Campaigne', to_date('14-07-2015', 'dd-mm-yyyy'), 66, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('795', 'Moon', 'War', 'Kacey Mullineux', to_date('24-09-2010', 'dd-mm-yyyy'), 114, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('994', 'Selma', 'Drama', 'Mona Cornbill', to_date('13-11-2008', 'dd-mm-yyyy'), 178, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('670', 'Alien', 'History', 'Gerek Houseago', to_date('19-04-2004', 'dd-mm-yyyy'), 108, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('711', 'Superbad', 'Biography', 'Rutter Hernik', to_date('06-11-2004', 'dd-mm-yyyy'), 100, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('297', 'Tombstone', 'Romance', 'Garold Bland', to_date('03-09-2012', 'dd-mm-yyyy'), 128, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('817', 'Singles', 'Biography', 'Benny Fairey', to_date('14-04-2021', 'dd-mm-yyyy'), 139, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('280', 'X-', 'Animation', 'Sidney MacTrustrie', to_date('27-10-2020', 'dd-mm-yyyy'), 112, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('399', 'Contact', 'Drama', 'Olympe Grombridge', to_date('01-04-2003', 'dd-mm-yyyy'), 111, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('373', 'Coco', 'Family', 'Broddie Peppard', to_date('06-02-2012', 'dd-mm-yyyy'), 60, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('868', 'Beetlejuice', 'Western', 'August Inderwick', to_date('16-09-2021', 'dd-mm-yyyy'), 79, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('183', 'Ratatouille', 'Musical', 'Mirabella Ravelus', to_date('29-10-2005', 'dd-mm-yyyy'), 114, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('758', 'Matilda', 'Adventure', 'Deva Labone', to_date('19-11-2001', 'dd-mm-yyyy'), 122, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('389', 'Kill Bill', 'Documentary', 'Carilyn Abramchik', to_date('05-10-2022', 'dd-mm-yyyy'), 87, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('024', 'Gravity', 'Drama', 'Reinaldo Gerish', to_date('24-11-2015', 'dd-mm-yyyy'), 122, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('684', 'Creed', 'War', 'Elsworth Cossins', to_date('14-06-2020', 'dd-mm-yyyy'), 145, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('872', 'Twister', 'Mystery', 'Jenda Beecham', to_date('22-12-2009', 'dd-mm-yyyy'), 142, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('557', 'Creed', 'War', 'Adaline Brader', to_date('29-09-2000', 'dd-mm-yyyy'), 77, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('175', 'Witness', 'Romance', 'Obadias Burghill', to_date('26-04-2003', 'dd-mm-yyyy'), 84, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('910', 'Hercules', 'Fantasy', 'Nanon Bartoszinski', to_date('18-07-2017', 'dd-mm-yyyy'), 123, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('010', 'Big Fish', 'Sport', 'Creighton Scholey', to_date('08-03-2006', 'dd-mm-yyyy'), 113, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('201', 'Gattaca', 'War', 'Eugenie McLanachan', to_date('04-09-2012', 'dd-mm-yyyy'), 172, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('683', 'Amadeus', 'War', 'Phineas Leftbridge', to_date('30-12-2018', 'dd-mm-yyyy'), 174, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('171', 'Chocolat', 'Action', 'Zed Gibling', to_date('27-02-2011', 'dd-mm-yyyy'), 177, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('713', 'Beetlejuice', 'Fantasy', 'Mariele Sayburn', to_date('27-11-2011', 'dd-mm-yyyy'), 134, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('319', 'Clueless', 'Musical', 'Norry Bradtke', to_date('25-05-2007', 'dd-mm-yyyy'), 176, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('923', 'Matilda', 'Fantasy', 'Antoine Gallehawk', to_date('25-07-2009', 'dd-mm-yyyy'), 79, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('274', 'Ted', 'Sport', 'Lauryn Merck', to_date('25-02-2011', 'dd-mm-yyyy'), 97, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('326', 'True Lies', 'Romance', 'Jeffrey Dunckley', to_date('04-07-2011', 'dd-mm-yyyy'), 121, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('842', 'Watchmen', 'Romance', 'Elnora Felstead', to_date('08-06-2003', 'dd-mm-yyyy'), 85, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('743', 'Patton', 'Crime', 'Elysha Mabbot', to_date('27-02-2012', 'dd-mm-yyyy'), 168, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('541', 'Sideways', 'Animation', 'Stacee Fullom', to_date('15-08-2008', 'dd-mm-yyyy'), 78, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('185', 'Hercules', 'Animation', 'Julianne Wegner', to_date('17-02-2007', 'dd-mm-yyyy'), 151, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('751', 'Labyrinth', 'Action', 'Oneida Labon', to_date('12-12-2018', 'dd-mm-yyyy'), 150, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('886', 'Iron Man', 'Romance', 'Minni Ternott', to_date('17-09-2012', 'dd-mm-yyyy'), 68, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('955', 'Notorious', 'Action', 'Frasco Ivashkin', to_date('10-10-2013', 'dd-mm-yyyy'), 162, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('849', 'Logan', 'Biography', 'Sherwin Dykes', to_date('17-07-2005', 'dd-mm-yyyy'), 150, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('162', 'Brave', 'Adventure', 'Nikoletta Bemrose', to_date('11-04-2015', 'dd-mm-yyyy'), 129, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('368', 'Cinderella', 'History', 'Ginger Rylatt', to_date('13-05-2017', 'dd-mm-yyyy'), 67, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('424', 'Witness', 'Fantasy', 'Chastity Wyche', to_date('01-08-2016', 'dd-mm-yyyy'), 177, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('891', 'Boyhood', 'Animation', 'Lishe Maddinon', to_date('05-05-2004', 'dd-mm-yyyy'), 73, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('526', 'Airplane', 'Musical', 'Rosalinda Molian', to_date('12-12-2011', 'dd-mm-yyyy'), 121, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('144', 'Arrival', 'Fantasy', 'Orella Browncey', to_date('20-05-2009', 'dd-mm-yyyy'), 67, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('968', 'Matilda', 'Biography', 'Shawnee Spofford', to_date('10-11-2016', 'dd-mm-yyyy'), 177, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('749', 'Crash', 'Comedy', 'Odell McKew', to_date('16-07-2010', 'dd-mm-yyyy'), 162, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('539', 'Rocky II', 'Drama', 'Lona Darrington', to_date('01-05-2002', 'dd-mm-yyyy'), 88, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('121', 'Inception', 'Documentary', 'Evin Sanderson', to_date('30-01-2023', 'dd-mm-yyyy'), 68, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('584', 'Cinderella', 'Comedy', 'Huntington Tardiff', to_date('10-09-2023', 'dd-mm-yyyy'), 115, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('272', 'Ben-Hur', 'Romance', 'Inessa Icom', to_date('26-12-2018', 'dd-mm-yyyy'), 178, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('424', 'Whiplash', 'History', 'Gerri Hurdle', to_date('26-10-2008', 'dd-mm-yyyy'), 112, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('078', 'Memento', 'Animation', 'Randall Filipic', to_date('08-12-2002', 'dd-mm-yyyy'), 137, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('590', 'Witness', 'Action', 'Ninon Bimson', to_date('10-11-2014', 'dd-mm-yyyy'), 95, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('421', 'Matilda', 'Biography', 'Corey Scholz', to_date('26-04-2012', 'dd-mm-yyyy'), 84, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('300', 'Iron Man', 'Drama', 'Roxanna Bruff', to_date('30-12-2003', 'dd-mm-yyyy'), 141, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('559', 'Frida', 'Action', 'Fulton Grimoldby', to_date('29-11-2009', 'dd-mm-yyyy'), 78, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('242', 'Platoon', 'Drama', 'Sapphira Truett', to_date('19-02-2009', 'dd-mm-yyyy'), 97, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('499', 'Boyhood', 'Musical', 'Brit Gentric', to_date('26-02-2013', 'dd-mm-yyyy'), 152, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('538', 'Whiplash', 'Sci-Fi', 'Mariana Scrogges', to_date('09-05-2016', 'dd-mm-yyyy'), 103, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('050', 'Cowboys', 'Comedy', 'Miller Incogna', to_date('06-03-2008', 'dd-mm-yyyy'), 66, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('684', 'Mad Max', 'Family', 'Jodie Decroix', to_date('06-07-2008', 'dd-mm-yyyy'), 99, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('883', 'Hancock', 'Fantasy', 'Petronella Cheston', to_date('02-04-2005', 'dd-mm-yyyy'), 100, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('228', 'Heat', 'Thriller', 'Meier Hercules', to_date('10-11-2010', 'dd-mm-yyyy'), 149, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('832', 'Rio', 'War', 'Roddie Iohananof', to_date('26-01-2005', 'dd-mm-yyyy'), 112, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('113', 'Coraline', 'Adventure', 'Aeriela Bockin', to_date('07-09-2006', 'dd-mm-yyyy'), 143, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('460', 'Bolt', 'Romance', 'Veronica Mahaddy', to_date('11-12-2007', 'dd-mm-yyyy'), 133, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('313', 'Stargate', 'Adventure', 'Bathsheba Gorini', to_date('20-10-2022', 'dd-mm-yyyy'), 76, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('005', 'Goonies', 'Adventure', 'Griffin Bettlestone', to_date('19-12-2015', 'dd-mm-yyyy'), 82, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('708', 'Amadeus', 'Comedy', 'Crissy Kelway', to_date('22-04-2001', 'dd-mm-yyyy'), 162, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('112', 'Star Trek', 'History', 'Sonya Hill', to_date('26-09-2000', 'dd-mm-yyyy'), 91, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('825', 'Looper', 'Thriller', 'Randal Carcas', to_date('30-09-2020', 'dd-mm-yyyy'), 87, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('958', 'Ted', 'Sport', 'Nicholas Dommett', to_date('07-08-2011', 'dd-mm-yyyy'), 76, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('342', 'Crash', 'Western', 'Brien Swale', to_date('04-02-2022', 'dd-mm-yyyy'), 148, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('414', 'Inception', 'Mystery', 'Goldy Charters', to_date('24-12-2012', 'dd-mm-yyyy'), 110, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('184', 'Ant-Man', 'Action', 'Karisa Pasfield', to_date('23-08-2004', 'dd-mm-yyyy'), 114, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('710', 'Hugo', 'Biography', 'Robbyn Braunroth', to_date('26-07-2002', 'dd-mm-yyyy'), 119, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('692', 'Godzilla', 'History', 'Del Goodricke', to_date('29-03-2019', 'dd-mm-yyyy'), 112, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('015', 'Rudy', 'Sport', 'Doro Grece', to_date('10-08-2000', 'dd-mm-yyyy'), 95, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('605', 'Coco', 'Thriller', 'Dale Tomisch', to_date('21-07-2001', 'dd-mm-yyyy'), 78, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('072', 'Dumbo', 'Horror', 'Kyla Harbach', to_date('06-12-2022', 'dd-mm-yyyy'), 171, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('826', 'Shutter', 'Musical', 'Sashenka Roles', to_date('09-02-2011', 'dd-mm-yyyy'), 121, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('165', 'Platoon', 'Horror', 'Valentine Drohane', to_date('10-06-2001', 'dd-mm-yyyy'), 115, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('150', 'Psycho', 'Biography', 'Fara Moffat', to_date('19-08-2017', 'dd-mm-yyyy'), 160, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('055', 'Speed', 'War', 'Ashlie Twycross', to_date('03-10-2018', 'dd-mm-yyyy'), 144, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('621', 'Airplane', 'Thriller', 'Dulcine Halpine', to_date('03-02-2024', 'dd-mm-yyyy'), 144, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('457', 'Labyrinth', 'Animation', 'Kissee Dunkerley', to_date('20-09-2012', 'dd-mm-yyyy'), 149, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('547', 'Fargo', 'Comedy', 'Willamina Ballard', to_date('25-02-2007', 'dd-mm-yyyy'), 93, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('673', 'Frida', 'Comedy', 'Moises Restall', to_date('02-11-2018', 'dd-mm-yyyy'), 82, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('348', 'Monsters', 'Adventure', 'Leonid Ogbourne', to_date('15-08-2007', 'dd-mm-yyyy'), 137, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('562', 'Witness', 'Fantasy', 'Bella Molson', to_date('29-01-2014', 'dd-mm-yyyy'), 160, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('675', 'Twister', 'Animation', 'Garry Demoge', to_date('06-11-2020', 'dd-mm-yyyy'), 180, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('432', 'Singles', 'Sport', 'Stevy Hirtz', to_date('15-11-2022', 'dd-mm-yyyy'), 88, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('744', 'Maverick', 'Thriller', 'Delly Cotterill', to_date('29-01-2012', 'dd-mm-yyyy'), 173, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('046', 'Casino', 'Western', 'Glenn Kolis', to_date('23-01-2014', 'dd-mm-yyyy'), 94, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('839', 'Crash', 'Biography', 'Terza Heard', to_date('31-08-2011', 'dd-mm-yyyy'), 100, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('622', 'Kill Bill', 'Documentary', 'Darnall Bausor', to_date('21-07-2002', 'dd-mm-yyyy'), 164, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('560', 'Psycho', 'Documentary', 'Iain Kew', to_date('27-09-2019', 'dd-mm-yyyy'), 119, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('783', 'Casino', 'History', 'Hakeem Nelm', to_date('24-12-2021', 'dd-mm-yyyy'), 132, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('848', 'Dumbo', 'History', 'Amelita Breitling', to_date('04-10-2016', 'dd-mm-yyyy'), 73, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('771', 'Aliens', 'Western', 'Bartholomeus Vaughan-Hughes', to_date('28-06-2012', 'dd-mm-yyyy'), 121, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('989', 'Crash', 'Thriller', 'Sonnie Callcott', to_date('11-10-2005', 'dd-mm-yyyy'), 60, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('334', 'Memento', 'Animation', 'Devlen Jefferys', to_date('09-12-2010', 'dd-mm-yyyy'), 123, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('847', 'Unforgiven', 'Sport', 'Hugues Nucciotti', to_date('14-03-2014', 'dd-mm-yyyy'), 139, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('294', 'Memento', 'War', 'Auberon Stollenbecker', to_date('12-04-2001', 'dd-mm-yyyy'), 120, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('356', 'Chappie', 'Comedy', 'Jenni Fontin', to_date('26-02-2017', 'dd-mm-yyyy'), 103, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('194', 'Singles', 'Animation', 'Arther MacIlhargy', to_date('22-05-2010', 'dd-mm-yyyy'), 97, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('725', 'Dune', 'Musical', 'Gorden Jurn', to_date('10-04-2018', 'dd-mm-yyyy'), 61, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('464', 'Notebook', 'Animation', 'Gerry Stammirs', to_date('27-07-2007', 'dd-mm-yyyy'), 105, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('480', 'Amelie', 'Documentary', 'Buckie Le Fevre', to_date('15-01-2013', 'dd-mm-yyyy'), 118, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('363', 'Moana', 'Adventure', 'Berny Lafford', to_date('15-02-2011', 'dd-mm-yyyy'), 72, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('071', 'Fury', 'Thriller', 'Terence Reddin', to_date('02-01-2006', 'dd-mm-yyyy'), 159, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('017', 'Xanadu', 'Biography', 'Natalina Di Francesco', to_date('16-02-2024', 'dd-mm-yyyy'), 106, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('711', 'Cop Land', 'Family', 'Sofie Cammell', to_date('17-04-2017', 'dd-mm-yyyy'), 105, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('328', 'Hercules', 'Animation', 'Oneida Oldrey', to_date('05-10-2017', 'dd-mm-yyyy'), 180, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('144', 'Psycho', 'War', 'Wyatan Ferenc', to_date('25-03-2001', 'dd-mm-yyyy'), 133, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('478', 'Giant', 'Biography', 'Erinn Hooke', to_date('14-06-2008', 'dd-mm-yyyy'), 151, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('527', 'Airplane', 'Sci-Fi', 'Tyrone Snoden', to_date('24-09-2018', 'dd-mm-yyyy'), 179, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('405', 'Dumbo', 'Adventure', 'Aldis Ertel', to_date('29-06-2011', 'dd-mm-yyyy'), 134, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('035', 'Heat', 'Musical', 'Chadwick Bernaert', to_date('14-07-2023', 'dd-mm-yyyy'), 121, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('570', 'Patton', 'Thriller', 'Sybille Shearstone', to_date('21-07-2003', 'dd-mm-yyyy'), 111, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('980', 'Stargate', 'Biography', 'Elbertine Flanne', to_date('27-08-2001', 'dd-mm-yyyy'), 174, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('573', 'Flubber', 'Documentary', 'Dierdre Franseco', to_date('08-09-2002', 'dd-mm-yyyy'), 102, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('122', 'Rango', 'Sci-Fi', 'Chic Solloway', to_date('05-05-2018', 'dd-mm-yyyy'), 167, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('331', 'Cowboys', 'Thriller', 'Jeni Maskew', to_date('25-10-2014', 'dd-mm-yyyy'), 168, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('339', 'Eraser', 'Family', 'Tracee Bampfield', to_date('23-05-2022', 'dd-mm-yyyy'), 130, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('570', 'Coco', 'Sport', 'Morgen Cullnean', to_date('12-03-2019', 'dd-mm-yyyy'), 130, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('597', 'Hugo', 'Comedy', 'Ignatius Legg', to_date('07-01-2007', 'dd-mm-yyyy'), 146, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('453', 'Aliens', 'Thriller', 'Igor Cumbridge', to_date('16-03-2006', 'dd-mm-yyyy'), 65, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('115', 'Sideways', 'Animation', 'Orin Hancock', to_date('28-06-2011', 'dd-mm-yyyy'), 155, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('057', 'Zodiac', 'Adventure', 'Ugo Boxen', to_date('09-05-2003', 'dd-mm-yyyy'), 71, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('211', 'Hancock', 'Sport', 'Beryle Fantin', to_date('25-05-2003', 'dd-mm-yyyy'), 97, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('919', 'Whiplash', 'Sci-Fi', 'Jenifer Lanchbury', to_date('13-10-2016', 'dd-mm-yyyy'), 72, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('272', 'Jaws', 'Comedy', 'Valentino Coghill', to_date('15-12-2007', 'dd-mm-yyyy'), 85, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('624', 'Clerks', 'Horror', 'Stern Swales', to_date('19-11-2005', 'dd-mm-yyyy'), 98, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('830', 'Witness', 'Horror', 'Worthy Roget', to_date('09-01-2010', 'dd-mm-yyyy'), 138, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('570', 'Logan', 'Documentary', 'Ros Palmar', to_date('01-05-2021', 'dd-mm-yyyy'), 100, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('556', 'Gattaca', 'Comedy', 'Geordie Shottin', to_date('20-07-2010', 'dd-mm-yyyy'), 133, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('927', 'True Lies', 'Adventure', 'Dionysus Vasilmanov', to_date('06-06-2023', 'dd-mm-yyyy'), 178, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('501', 'True Lies', 'Romance', 'Creigh Domenge', to_date('24-01-2012', 'dd-mm-yyyy'), 147, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('336', 'Mulan', 'Adventure', 'Frederica Wathall', to_date('16-03-2016', 'dd-mm-yyyy'), 131, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('369', 'Dune', 'Crime', 'Marris Aulsford', to_date('03-12-2023', 'dd-mm-yyyy'), 154, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('931', 'Kill Bill', 'Comedy', 'Mikol Leavesley', to_date('03-08-2018', 'dd-mm-yyyy'), 78, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('678', 'Amadeus', 'Thriller', 'Roxie Le - Count', to_date('20-09-2001', 'dd-mm-yyyy'), 122, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('118', 'Big', 'Drama', 'Elvira Wainman', to_date('16-05-2020', 'dd-mm-yyyy'), 130, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('711', 'Coco', 'Fantasy', 'Oralla Derisley', to_date('15-08-2019', 'dd-mm-yyyy'), 158, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('715', 'Fargo', 'Drama', 'Abie Salisbury', to_date('30-03-2004', 'dd-mm-yyyy'), 105, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('623', 'Whiplash', 'Mystery', 'Gene Spellecy', to_date('09-11-2017', 'dd-mm-yyyy'), 66, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('220', 'Avatar', 'Sci-Fi', 'Dur Dearnly', to_date('22-12-2010', 'dd-mm-yyyy'), 124, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('111', 'Hackers', 'Mystery', 'Bax Middup', to_date('12-11-2019', 'dd-mm-yyyy'), 116, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('292', 'Singles', 'Action', 'Shirl Normansell', to_date('26-09-2013', 'dd-mm-yyyy'), 125, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('951', 'Godzilla', 'Crime', 'Arabella Davitt', to_date('14-03-2021', 'dd-mm-yyyy'), 106, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('144', 'Gattaca', 'Thriller', 'Saxe Daborn', to_date('22-10-2006', 'dd-mm-yyyy'), 60, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('724', 'Split', 'Sci-Fi', 'Birgitta Lequeux', to_date('11-09-2022', 'dd-mm-yyyy'), 117, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('744', 'Psycho', 'Comedy', 'Briney Sill', to_date('04-10-2003', 'dd-mm-yyyy'), 143, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('341', 'Logan', 'Fantasy', 'Gunilla Aldcorne', to_date('19-10-2000', 'dd-mm-yyyy'), 79, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('018', 'Unforgiven', 'Comedy', 'Francyne Mallatratt', to_date('10-02-2007', 'dd-mm-yyyy'), 100, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('914', 'Lincoln', 'Documentary', 'Morton Oakeby', to_date('21-05-2023', 'dd-mm-yyyy'), 156, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('345', 'Ali', 'Musical', 'Diego Earnshaw', to_date('30-08-2010', 'dd-mm-yyyy'), 103, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('864', 'Clerks', 'Comedy', 'Northrop Khotler', to_date('08-02-2015', 'dd-mm-yyyy'), 160, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('130', 'Titanic', 'Horror', 'Daven Craven', to_date('28-08-2011', 'dd-mm-yyyy'), 60, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('424', 'Notorious', 'Musical', 'Dottie Maymond', to_date('09-11-2016', 'dd-mm-yyyy'), 123, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('304', 'Braveheart', 'Drama', 'Emile Korn', to_date('03-03-2004', 'dd-mm-yyyy'), 132, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('661', 'Gigi', 'Action', 'Sela Rubinfeld', to_date('12-10-2004', 'dd-mm-yyyy'), 128, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('984', 'Frozen', 'Horror', 'Tannie Bedwell', to_date('22-02-2020', 'dd-mm-yyyy'), 71, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('560', 'Clueless', 'Thriller', 'Ravid Pawsey', to_date('14-05-2005', 'dd-mm-yyyy'), 94, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('088', 'Babe', 'Mystery', 'Will Yates', to_date('03-08-2009', 'dd-mm-yyyy'), 111, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('849', 'Frozen', 'Mystery', 'Tiffani Shavel', to_date('17-01-2022', 'dd-mm-yyyy'), 127, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('188', 'Monsters', 'Family', 'Dalli Bellsham', to_date('15-10-2020', 'dd-mm-yyyy'), 104, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('503', 'Looper', 'Documentary', 'Victor Sparrowe', to_date('02-09-2023', 'dd-mm-yyyy'), 125, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('371', 'Black Swan', 'Action', 'Luisa Cudihy', to_date('26-04-2020', 'dd-mm-yyyy'), 103, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('120', 'Kill Bill', 'Fantasy', 'Kordula Cotte', to_date('28-02-2014', 'dd-mm-yyyy'), 106, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('029', 'Skyfall', 'Romance', 'Chelsae De la Zenne', to_date('17-02-2015', 'dd-mm-yyyy'), 138, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('354', 'Twister', 'Western', 'Lonee Norcross', to_date('06-06-2023', 'dd-mm-yyyy'), 84, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('744', 'Chappie', 'Mystery', 'Nonah Derycot', to_date('17-01-2009', 'dd-mm-yyyy'), 78, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('083', 'Signs', 'Western', 'Nikolos McAnellye', to_date('27-04-2016', 'dd-mm-yyyy'), 93, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('446', 'Matilda', 'Family', 'Marjie Enoksson', to_date('05-09-2019', 'dd-mm-yyyy'), 176, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('553', 'Trumbo', 'Mystery', 'Lothario Fero', to_date('28-01-2011', 'dd-mm-yyyy'), 144, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('517', 'Arrival', 'Drama', 'Daveen Nice', to_date('29-03-2007', 'dd-mm-yyyy'), 94, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('365', 'Beetlejuice', 'Thriller', 'Ado Garrold', to_date('01-01-2023', 'dd-mm-yyyy'), 97, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('415', 'Boyhood', 'Sci-Fi', 'Smith Hitschke', to_date('20-01-2003', 'dd-mm-yyyy'), 78, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('386', 'Ted', 'Family', 'Rhiamon Forre', to_date('30-10-2002', 'dd-mm-yyyy'), 146, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('360', 'Tombstone', 'Fantasy', 'Lenora Gianolini', to_date('25-07-2019', 'dd-mm-yyyy'), 144, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('771', 'Tombstone', 'Sport', 'Christian Greenrde', to_date('17-04-2016', 'dd-mm-yyyy'), 81, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('927', 'Grease', 'Family', 'Shaine Corbridge', to_date('22-08-2013', 'dd-mm-yyyy'), 160, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('609', 'Witness', 'Biography', 'Regan Capron', to_date('17-12-2001', 'dd-mm-yyyy'), 104, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('052', 'Hancock', 'Animation', 'Sarette Bywaters', to_date('21-07-2020', 'dd-mm-yyyy'), 68, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('833', 'Boyhood', 'Mystery', 'Vivyan Rookesby', to_date('30-09-2016', 'dd-mm-yyyy'), 109, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('379', 'Lincoln', 'History', 'Carol-jean Jain', to_date('06-11-2013', 'dd-mm-yyyy'), 165, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('384', 'Clerks', 'Family', 'Beryl Rubel', to_date('10-12-2004', 'dd-mm-yyyy'), 128, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('142', 'Twister', 'Musical', 'Gradey Loweth', to_date('05-04-2013', 'dd-mm-yyyy'), 146, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('516', 'Rushmore', 'Sport', 'Irena Fletcher', to_date('11-01-2023', 'dd-mm-yyyy'), 141, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('904', 'Elf', 'Animation', 'Elisabet Stainer', to_date('16-03-2021', 'dd-mm-yyyy'), 115, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('099', 'Twister', 'Sport', 'Florella Fetherstone', to_date('25-05-2011', 'dd-mm-yyyy'), 72, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('723', 'District 9', 'Action', 'Tommy Katzmann', to_date('26-07-2023', 'dd-mm-yyyy'), 123, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('504', 'Unforgiven', 'War', 'Jarrad Tunstall', to_date('01-12-2016', 'dd-mm-yyyy'), 133, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('837', 'Amadeus', 'Mystery', 'Marice Juszczyk', to_date('09-10-2008', 'dd-mm-yyyy'), 133, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('776', 'Sideways', 'History', 'Dedra Hicklingbottom', to_date('14-01-2011', 'dd-mm-yyyy'), 113, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('358', 'Tombstone', 'Mystery', 'Cullan Coarser', to_date('02-11-2006', 'dd-mm-yyyy'), 121, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('339', 'Creed', 'Documentary', 'Jake Perel', to_date('23-06-2005', 'dd-mm-yyyy'), 127, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('550', 'Airplane', 'Mystery', 'Damita de Leon', to_date('06-08-2018', 'dd-mm-yyyy'), 104, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('431', 'Logan', 'Action', 'Barnett Jermin', to_date('01-02-2011', 'dd-mm-yyyy'), 114, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('176', 'Bolt', 'Comedy', 'Lolly Fidell', to_date('29-09-2002', 'dd-mm-yyyy'), 127, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('681', 'Iron Man', 'Horror', 'Katie Glazebrook', to_date('19-02-2017', 'dd-mm-yyyy'), 64, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('943', 'Twister', 'Horror', 'Panchito Pantecost', to_date('16-04-2004', 'dd-mm-yyyy'), 137, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('755', 'Matilda', 'Mystery', 'Don Scrafton', to_date('21-08-2019', 'dd-mm-yyyy'), 84, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('310', 'Casino', 'Family', 'Kathye Saterweyte', to_date('04-07-2021', 'dd-mm-yyyy'), 163, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('485', 'Flubber', 'History', 'Brigham Haquard', to_date('21-06-2021', 'dd-mm-yyyy'), 113, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('639', 'Shutter', 'Musical', 'Jaynell Cressor', to_date('14-07-2018', 'dd-mm-yyyy'), 167, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('031', 'Amadeus', 'Horror', 'Blondell Dearnaly', to_date('21-09-2013', 'dd-mm-yyyy'), 82, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('961', 'Brave', 'Animation', 'Munroe Thams', to_date('19-10-2004', 'dd-mm-yyyy'), 90, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('030', 'Creed', 'History', 'Dulce Goodburn', to_date('17-01-2008', 'dd-mm-yyyy'), 178, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('110', 'Rushmore', 'Comedy', 'Leila Florez', to_date('23-03-2015', 'dd-mm-yyyy'), 113, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('829', 'Big', 'Crime', 'Aurilia Kliment', to_date('08-11-2011', 'dd-mm-yyyy'), 178, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('155', 'Rango', 'History', 'Tine Redgate', to_date('17-08-2011', 'dd-mm-yyyy'), 170, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('693', 'Whiplash', 'Sport', 'Celestyn Chesshire', to_date('02-02-2012', 'dd-mm-yyyy'), 147, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('390', 'Ted', 'Sci-Fi', 'Roxie Rennocks', to_date('22-08-2006', 'dd-mm-yyyy'), 78, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('070', 'Contact', 'Horror', 'Oralla Chimienti', to_date('03-11-2012', 'dd-mm-yyyy'), 172, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('841', 'Rushmore', 'Thriller', 'Camellia Creagh', to_date('04-02-2018', 'dd-mm-yyyy'), 64, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('691', 'Holes', 'Family', 'Gustavo Gadault', to_date('12-09-2014', 'dd-mm-yyyy'), 60, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('792', 'Tombstone', 'Sci-Fi', 'Sandra Buff', to_date('01-01-2003', 'dd-mm-yyyy'), 171, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('574', 'Rocky II', 'Documentary', 'Hadria Aleksankin', to_date('14-07-2010', 'dd-mm-yyyy'), 166, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('635', 'Hercules', 'Animation', 'Ariana Wright', to_date('02-07-2000', 'dd-mm-yyyy'), 63, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('692', 'Twister', 'Sport', 'Federico Sutherley', to_date('10-04-2013', 'dd-mm-yyyy'), 131, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('273', 'Moana', 'Adventure', 'Waylen Mulbry', to_date('02-01-2003', 'dd-mm-yyyy'), 101, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('690', 'Doubt', 'Adventure', 'Modesta Daunter', to_date('25-03-2019', 'dd-mm-yyyy'), 65, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('922', 'Babe', 'Sci-Fi', 'Hagan De Roos', to_date('23-01-2001', 'dd-mm-yyyy'), 105, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('407', 'Speed', 'Fantasy', 'Merola Melley', to_date('20-06-2023', 'dd-mm-yyyy'), 132, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('284', 'Rent', 'Adventure', 'Angy Keeble', to_date('06-10-2003', 'dd-mm-yyyy'), 168, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('667', 'Monsters', 'Musical', 'Cristabel Orring', to_date('19-12-2004', 'dd-mm-yyyy'), 145, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('155', 'Ali', 'Fantasy', 'Miranda Da Costa', to_date('09-01-2014', 'dd-mm-yyyy'), 85, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('604', 'Speed', 'History', 'Hendrick Abrahim', to_date('01-01-2005', 'dd-mm-yyyy'), 154, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('892', 'Heat', 'Family', 'Pedro Mephan', to_date('30-06-2005', 'dd-mm-yyyy'), 132, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('312', 'Singles', 'Mystery', 'Loy Barhem', to_date('26-11-2002', 'dd-mm-yyyy'), 89, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('256', 'Taken', 'History', 'Barbabra Limpertz', to_date('24-05-2011', 'dd-mm-yyyy'), 164, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('871', 'Eraser', 'Documentary', 'Bernette MacAlpin', to_date('03-12-2006', 'dd-mm-yyyy'), 103, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('115', 'Lincoln', 'History', 'Morey Dafydd', to_date('30-10-2021', 'dd-mm-yyyy'), 123, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('775', 'Nim''s Island', 'Thriller', 'Meridel Graal', to_date('16-06-2007', 'dd-mm-yyyy'), 136, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('361', 'Ted', 'War', 'Flo Rolfi', to_date('20-01-2008', 'dd-mm-yyyy'), 80, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('023', 'Birdman', 'Drama', 'Marlee Gerssam', to_date('23-09-2017', 'dd-mm-yyyy'), 72, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('793', 'Doubt', 'Comedy', 'Verla Street', to_date('23-07-2017', 'dd-mm-yyyy'), 137, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('970', 'Nim''s Island', 'Animation', 'Avivah Bucknell', to_date('26-03-2016', 'dd-mm-yyyy'), 144, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('606', 'Poltergeist', 'Family', 'Bron Boustred', to_date('28-06-2004', 'dd-mm-yyyy'), 129, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('495', 'Gremlins', 'War', 'Shelley Traill', to_date('22-01-2005', 'dd-mm-yyyy'), 113, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('655', 'Kill Bill', 'Thriller', 'Fionnula Olliver', to_date('28-08-2007', 'dd-mm-yyyy'), 150, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('038', 'Eraser', 'Drama', 'Elonore Moulsdale', to_date('13-07-2019', 'dd-mm-yyyy'), 83, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('191', 'Gremlins', 'History', 'Elisa Kippin', to_date('04-08-2009', 'dd-mm-yyyy'), 101, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('698', 'Unbroken', 'Mystery', 'Dita Runnicles', to_date('19-08-2013', 'dd-mm-yyyy'), 60, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('722', 'Boyhood', 'Drama', 'Devora Cubin', to_date('09-07-2015', 'dd-mm-yyyy'), 79, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('512', 'Cinderella', 'Comedy', 'Melvin Bloxsom', to_date('19-08-2011', 'dd-mm-yyyy'), 146, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('706', 'Hugo', 'Action', 'Chalmers Greim', to_date('08-09-2009', 'dd-mm-yyyy'), 85, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('117', 'Ali', 'Biography', 'Bibby Wherrit', to_date('07-11-2002', 'dd-mm-yyyy'), 68, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('534', 'Rudy', 'Adventure', 'Aldin Brownell', to_date('02-06-2010', 'dd-mm-yyyy'), 142, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('181', 'Sin City', 'Mystery', 'Rufe Wimpenny', to_date('28-02-2001', 'dd-mm-yyyy'), 129, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('506', 'Doubt', 'Comedy', 'Roxy Hankin', to_date('20-02-2024', 'dd-mm-yyyy'), 142, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('677', 'Gladiator', 'Fantasy', 'Donalt Antoni', to_date('27-12-2012', 'dd-mm-yyyy'), 128, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('846', 'Witness', 'War', 'Fin Pottell', to_date('28-09-2004', 'dd-mm-yyyy'), 113, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('078', 'Alien', 'Documentary', 'Krispin Nornable', to_date('16-03-2023', 'dd-mm-yyyy'), 88, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('079', 'Amadeus', 'Documentary', 'Manya Bewshea', to_date('26-08-2003', 'dd-mm-yyyy'), 130, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('774', 'Tombstone', 'Family', 'Bernetta Durtnell', to_date('05-05-2006', 'dd-mm-yyyy'), 71, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('742', 'Unforgiven', 'Mystery', 'Blisse Keinrat', to_date('31-03-2017', 'dd-mm-yyyy'), 74, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('668', 'Witness', 'Biography', 'Davis McPhail', to_date('06-01-2003', 'dd-mm-yyyy'), 147, 2);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('878', 'Gladiator', 'Action', 'Hermia Semmence', to_date('13-04-2002', 'dd-mm-yyyy'), 167, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('653', 'Aliens', 'Western', 'Rahal Bangham', to_date('21-03-2024', 'dd-mm-yyyy'), 129, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('103', 'Unforgiven', 'Horror', 'Cord Hansemann', to_date('10-01-2002', 'dd-mm-yyyy'), 93, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('030', 'Hancock', 'Thriller', 'Kathy Costan', to_date('14-11-2009', 'dd-mm-yyyy'), 164, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('689', 'Mad Max', 'Crime', 'Vlad Laise', to_date('15-10-2007', 'dd-mm-yyyy'), 165, 7);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('167', 'Gigi', 'Musical', 'Odille Hrihorovich', to_date('17-01-2012', 'dd-mm-yyyy'), 61, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('379', 'Whiplash', 'Thriller', 'Tove Huggens', to_date('20-06-2007', 'dd-mm-yyyy'), 180, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('348', 'Creed', 'History', 'Munroe Stienton', to_date('29-05-2020', 'dd-mm-yyyy'), 178, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('746', 'Taken', 'Crime', 'Arron Callicott', to_date('28-05-2018', 'dd-mm-yyyy'), 87, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('237', 'Aliens', 'Drama', 'Alvira Rewcassell', to_date('04-01-2008', 'dd-mm-yyyy'), 133, 4);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('608', 'Manhunter', 'Drama', 'Nikola Slaight', to_date('27-10-2021', 'dd-mm-yyyy'), 111, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('774', 'Avatar', 'Fantasy', 'Karlens Lyddiard', to_date('28-02-2024', 'dd-mm-yyyy'), 106, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('268', 'Ted', 'History', 'Jarvis Shankland', to_date('05-05-2019', 'dd-mm-yyyy'), 160, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('430', 'Rushmore', 'Action', 'Babette Glassup', to_date('04-08-2008', 'dd-mm-yyyy'), 179, 8);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('127', 'Gremlins', 'Western', 'Meredeth Sainsbury', to_date('14-06-2004', 'dd-mm-yyyy'), 107, 9);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('620', 'Moana', 'Documentary', 'Mirabel Bonnesen', to_date('17-02-2015', 'dd-mm-yyyy'), 174, 1);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('081', 'Memento', 'Western', 'Cinda Timblett', to_date('26-10-2019', 'dd-mm-yyyy'), 66, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('939', 'Twister', 'Biography', 'Faith Verrell', to_date('18-01-2017', 'dd-mm-yyyy'), 157, 10);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('546', 'Grease', 'Horror', 'Marilee Fouch', to_date('01-07-2014', 'dd-mm-yyyy'), 70, 5);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('407', 'Hackers', 'Adventure', 'Adah Lamborn', to_date('01-06-2016', 'dd-mm-yyyy'), 144, 6);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('672', 'Nim''s Island', 'Fantasy', 'Hilliary Abbey', to_date('02-10-2013', 'dd-mm-yyyy'), 94, 3);
insert into Movies (MovieID, Title , Genre, Director, ReleaseDate, Duration, Rating) values ('521', 'Crash', 'History', 'Filip Walewicz', to_date('22-08-2023', 'dd-mm-yyyy'), 76, 4);
commit;