insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (100, 30, 'N', 413, 407);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (101, 50, 'N', 343, 400);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (102, 30, 'N', 347, 129);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (103, 30, 'N', 344, 309);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (104, 30, 'N', 295, 342);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (105, 50, 'N', 317, 233);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (106, 30, 'N', 310, 432);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (107, 30, 'N', 262, 194);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (108, 30, 'N', 227, 363);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (109, 90, 'N', 305, 158);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (110, 30, 'N', 251, 470);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (111, 50, 'N', 414, 243);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (112, 90, 'N', 239, 270);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (113, 30, 'N', 248, 346);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (114, 30, 'N', 311, 317);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (115, 30, 'N', 332, 400);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (116, 30, 'N', 378, 259);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (117, 30, 'N', 145, 455);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (118, 30, 'N', 207, 336);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (119, 50, 'N', 348, 184);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (120, 90, 'N', 403, 298);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (121, 90, 'N', 327, 212);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (122, 30, 'N', 312, 146);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (123, 30, 'N', 263, 473);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (124, 90, 'N', 463, 303);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (125, 30, 'N', 133, 386);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (126, 30, 'N', 321, 403);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (127, 30, 'N', 425, 468);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (128, 30, 'N', 173, 312);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (129, 30, 'N', 187, 157);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (130, 30, 'N', 334, 169);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (131, 50, 'N', 399, 276);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (132, 30, 'N', 485, 259);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (133, 30, 'N', 269, 103);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (134, 50, 'N', 327, 297);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (135, 50, 'N', 451, 284);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (136, 30, 'N', 368, 153);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (137, 30, 'N', 394, 362);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (138, 30, 'N', 429, 394);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (139, 30, 'N', 214, 130);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (140, 30, 'N', 279, 248);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (141, 30, 'N', 285, 417);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (142, 30, 'N', 393, 204);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (143, 30, 'N', 167, 483);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (144, 50, 'N', 438, 422);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (145, 30, 'N', 447, 463);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (146, 30, 'N', 278, 181);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (147, 90, 'N', 312, 412);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (148, 90, 'N', 309, 348);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (149, 50, 'N', 444, 391);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (150, 30, 'N', 317, 465);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (151, 30, 'N', 444, 368);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (152, 90, 'N', 465, 473);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (153, 30, 'N', 374, 354);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (154, 30, 'N', 396, 251);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (155, 30, 'N', 430, 353);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (156, 90, 'N', 472, 189);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (157, 30, 'N', 341, 147);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (158, 30, 'N', 328, 376);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (159, 50, 'N', 483, 500);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (160, 30, 'N', 359, 416);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (161, 30, 'N', 334, 183);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (162, 30, 'N', 128, 279);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (163, 30, 'N', 236, 442);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (164, 30, 'N', 496, 164);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (165, 30, 'N', 100, 464);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (166, 30, 'N', 287, 191);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (167, 30, 'N', 219, 294);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (168, 50, 'N', 266, 320);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (169, 50, 'N', 219, 358);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (170, 30, 'N', 449, 498);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (171, 50, 'N', 130, 423);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (172, 30, 'N', 341, 217);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (173, 90, 'N', 379, 375);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (174, 30, 'N', 486, 320);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (175, 90, 'N', 315, 425);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (176, 30, 'N', 158, 209);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (177, 30, 'N', 451, 340);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (178, 30, 'N', 369, 493);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (179, 90, 'N', 440, 498);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (180, 30, 'N', 196, 250);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (181, 30, 'N', 366, 370);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (182, 50, 'N', 448, 129);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (183, 30, 'N', 167, 421);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (184, 50, 'N', 244, 463);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (185, 30, 'N', 385, 246);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (186, 30, 'N', 124, 409);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (187, 30, 'N', 229, 124);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (188, 30, 'N', 483, 120);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (189, 30, 'N', 179, 395);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (190, 30, 'N', 127, 341);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (191, 30, 'N', 303, 268);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (192, 50, 'N', 159, 217);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (193, 50, 'N', 304, 454);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (194, 30, 'N', 386, 146);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (195, 30, 'N', 489, 416);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (196, 90, 'N', 256, 444);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (197, 30, 'N', 470, 254);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (198, 30, 'N', 310, 232);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (199, 90, 'N', 381, 409);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (200, 50, 'N', 172, 164);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (201, 30, 'N', 225, 392);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (202, 30, 'N', 256, 163);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (203, 30, 'N', 145, 141);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (204, 30, 'N', 397, 190);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (205, 30, 'N', 421, 405);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (206, 30, 'N', 213, 440);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (207, 90, 'N', 391, 139);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (208, 50, 'N', 384, 154);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (209, 30, 'N', 296, 147);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (210, 30, 'N', 467, 271);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (211, 30, 'N', 451, 128);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (212, 50, 'N', 424, 287);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (213, 50, 'N', 144, 363);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (214, 90, 'N', 284, 153);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (215, 90, 'N', 253, 416);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (216, 50, 'N', 324, 392);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (217, 30, 'N', 394, 464);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (218, 30, 'N', 181, 440);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (219, 30, 'N', 194, 459);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (220, 90, 'N', 482, 418);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (221, 50, 'N', 283, 301);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (222, 50, 'N', 203, 320);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (223, 90, 'N', 219, 247);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (224, 90, 'N', 156, 237);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (225, 30, 'N', 131, 341);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (226, 30, 'N', 195, 394);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (227, 30, 'N', 492, 471);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (228, 30, 'N', 148, 220);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (229, 30, 'N', 415, 244);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (230, 30, 'N', 480, 444);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (231, 30, 'N', 473, 301);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (232, 50, 'N', 273, 208);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (233, 30, 'N', 447, 235);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (234, 90, 'N', 134, 415);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (235, 30, 'N', 394, 360);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (236, 50, 'N', 433, 491);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (237, 30, 'N', 246, 479);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (238, 50, 'N', 458, 184);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (239, 30, 'N', 330, 500);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (240, 90, 'N', 499, 380);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (241, 30, 'N', 414, 458);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (242, 30, 'N', 457, 141);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (243, 30, 'N', 479, 376);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (244, 30, 'N', 177, 382);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (245, 30, 'N', 413, 344);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (246, 90, 'N', 310, 157);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (247, 30, 'N', 235, 423);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (248, 30, 'N', 491, 381);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (249, 50, 'N', 437, 377);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (250, 30, 'N', 451, 166);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (251, 30, 'N', 460, 428);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (252, 90, 'N', 451, 202);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (253, 30, 'N', 487, 236);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (254, 50, 'N', 240, 336);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (255, 90, 'N', 165, 106);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (256, 30, 'N', 135, 197);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (257, 30, 'N', 250, 418);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (258, 30, 'N', 237, 442);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (259, 90, 'N', 379, 479);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (260, 30, 'N', 158, 214);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (261, 30, 'N', 168, 409);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (262, 30, 'N', 483, 447);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (263, 30, 'N', 429, 442);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (264, 30, 'N', 351, 173);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (265, 30, 'N', 119, 461);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (266, 30, 'N', 367, 273);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (267, 50, 'N', 210, 148);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (268, 30, 'N', 433, 240);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (269, 30, 'N', 487, 169);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (270, 30, 'N', 107, 376);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (271, 30, 'N', 466, 377);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (272, 50, 'N', 288, 206);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (273, 90, 'N', 441, 243);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (274, 30, 'N', 223, 323);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (275, 30, 'N', 259, 312);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (276, 30, 'N', 240, 457);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (277, 30, 'N', 208, 284);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (278, 30, 'N', 210, 164);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (279, 30, 'N', 447, 116);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (280, 50, 'N', 127, 151);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (281, 30, 'N', 147, 158);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (282, 30, 'N', 418, 211);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (283, 30, 'N', 361, 304);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (284, 30, 'N', 377, 196);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (285, 30, 'N', 225, 174);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (286, 90, 'N', 322, 409);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (287, 30, 'N', 475, 320);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (288, 30, 'N', 281, 220);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (289, 50, 'N', 294, 456);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (290, 90, 'N', 398, 112);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (291, 30, 'N', 285, 311);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (292, 30, 'N', 270, 349);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (293, 30, 'N', 363, 317);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (294, 90, 'N', 402, 263);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (295, 30, 'N', 182, 104);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (296, 50, 'N', 192, 180);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (297, 30, 'N', 475, 441);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (298, 90, 'N', 439, 360);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (299, 30, 'N', 129, 179);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (300, 30, 'N', 380, 160);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (301, 30, 'N', 180, 247);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (302, 30, 'N', 443, 237);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (303, 90, 'N', 334, 243);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (304, 30, 'N', 336, 155);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (305, 30, 'N', 412, 476);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (306, 30, 'N', 449, 239);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (307, 90, 'N', 324, 209);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (308, 50, 'N', 197, 432);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (309, 30, 'N', 163, 154);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (310, 30, 'N', 469, 195);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (311, 30, 'N', 425, 366);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (312, 50, 'N', 218, 226);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (313, 30, 'N', 358, 379);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (314, 50, 'N', 367, 396);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (315, 30, 'N', 431, 358);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (316, 50, 'N', 242, 322);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (317, 90, 'N', 131, 485);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (318, 50, 'N', 133, 162);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (319, 90, 'N', 284, 157);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (320, 50, 'N', 376, 428);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (321, 50, 'N', 299, 225);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (322, 30, 'N', 162, 430);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (323, 90, 'N', 343, 240);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (324, 30, 'N', 468, 145);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (325, 50, 'N', 436, 342);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (326, 30, 'N', 322, 315);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (327, 30, 'N', 468, 160);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (328, 30, 'N', 379, 353);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (329, 50, 'N', 350, 345);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (330, 30, 'N', 236, 497);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (331, 30, 'N', 285, 325);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (332, 50, 'N', 260, 172);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (333, 90, 'N', 358, 284);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (334, 50, 'N', 352, 188);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (335, 30, 'N', 267, 171);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (336, 50, 'N', 426, 351);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (337, 50, 'N', 360, 126);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (338, 30, 'N', 221, 111);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (339, 50, 'N', 410, 339);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (340, 30, 'N', 432, 230);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (341, 30, 'N', 112, 327);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (342, 30, 'N', 371, 273);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (343, 90, 'N', 102, 446);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (344, 30, 'N', 148, 326);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (345, 30, 'N', 306, 411);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (346, 30, 'N', 182, 141);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (347, 30, 'N', 406, 464);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (348, 30, 'N', 432, 101);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (349, 30, 'N', 441, 342);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (350, 30, 'N', 159, 417);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (351, 30, 'N', 326, 493);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (352, 50, 'N', 207, 140);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (353, 30, 'N', 298, 300);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (354, 30, 'N', 212, 413);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (355, 30, 'N', 290, 137);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (356, 30, 'N', 337, 326);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (357, 30, 'N', 220, 456);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (358, 90, 'N', 327, 223);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (359, 90, 'N', 420, 281);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (360, 90, 'N', 298, 412);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (361, 30, 'N', 179, 348);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (362, 50, 'N', 440, 106);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (363, 30, 'N', 411, 458);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (364, 30, 'N', 456, 199);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (365, 30, 'N', 457, 253);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (366, 30, 'N', 316, 252);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (367, 90, 'N', 201, 232);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (368, 50, 'N', 344, 113);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (369, 50, 'N', 319, 167);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (370, 30, 'N', 222, 161);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (371, 50, 'N', 250, 172);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (372, 30, 'N', 130, 173);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (373, 30, 'N', 290, 375);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (374, 50, 'N', 400, 419);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (375, 30, 'N', 214, 426);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (376, 30, 'N', 101, 174);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (377, 30, 'N', 424, 427);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (378, 30, 'N', 147, 471);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (379, 30, 'N', 418, 491);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (380, 30, 'N', 131, 256);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (381, 90, 'N', 187, 116);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (382, 50, 'N', 484, 396);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (383, 30, 'N', 135, 196);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (384, 30, 'N', 358, 282);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (385, 30, 'N', 327, 451);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (386, 90, 'N', 435, 285);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (387, 30, 'N', 258, 276);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (388, 90, 'N', 260, 413);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (389, 30, 'N', 350, 230);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (390, 30, 'N', 102, 412);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (391, 30, 'N', 374, 138);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (392, 30, 'N', 132, 480);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (393, 30, 'N', 395, 219);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (394, 30, 'N', 137, 210);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (395, 90, 'N', 243, 448);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (396, 30, 'N', 153, 162);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (397, 30, 'N', 310, 125);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (398, 30, 'N', 421, 451);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (399, 30, 'N', 470, 497);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (400, 90, 'N', 273, 364);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (401, 30, 'N', 325, 371);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (402, 30, 'N', 337, 211);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (403, 50, 'N', 379, 382);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (404, 50, 'N', 475, 183);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (405, 90, 'N', 130, 268);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (406, 30, 'N', 241, 254);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (407, 30, 'N', 293, 378);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (408, 30, 'N', 262, 292);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (409, 30, 'N', 347, 198);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (410, 30, 'N', 147, 405);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (411, 30, 'N', 203, 312);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (412, 50, 'N', 123, 308);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (413, 30, 'N', 405, 179);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (414, 30, 'N', 391, 119);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (415, 30, 'N', 447, 141);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (416, 30, 'N', 212, 174);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (417, 30, 'N', 419, 450);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (418, 30, 'N', 313, 267);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (419, 30, 'N', 382, 125);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (420, 50, 'N', 223, 327);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (421, 30, 'N', 260, 437);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (422, 50, 'N', 130, 100);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (423, 50, 'N', 263, 204);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (424, 30, 'N', 465, 277);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (425, 90, 'N', 233, 132);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (426, 50, 'N', 411, 230);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (427, 30, 'N', 315, 168);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (428, 90, 'N', 136, 384);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (429, 30, 'N', 152, 273);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (430, 30, 'N', 352, 406);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (431, 30, 'N', 207, 239);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (432, 30, 'N', 398, 427);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (433, 90, 'N', 412, 108);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (434, 30, 'N', 449, 483);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (435, 30, 'N', 132, 441);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (436, 90, 'N', 252, 182);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (437, 50, 'N', 268, 381);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (438, 90, 'N', 379, 202);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (439, 30, 'N', 275, 375);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (440, 30, 'N', 415, 401);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (441, 30, 'N', 109, 296);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (442, 50, 'N', 466, 166);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (443, 30, 'N', 295, 199);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (444, 30, 'N', 392, 179);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (445, 30, 'N', 129, 104);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (446, 50, 'N', 365, 411);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (447, 90, 'N', 394, 399);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (448, 30, 'N', 354, 337);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (449, 30, 'N', 209, 470);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (450, 30, 'N', 131, 182);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (451, 30, 'N', 397, 360);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (452, 30, 'N', 209, 391);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (453, 30, 'N', 185, 247);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (454, 30, 'N', 497, 111);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (455, 90, 'N', 422, 150);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (456, 30, 'N', 283, 328);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (457, 30, 'N', 128, 259);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (458, 50, 'N', 347, 389);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (459, 30, 'N', 361, 290);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (460, 30, 'N', 388, 385);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (461, 30, 'N', 217, 268);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (462, 30, 'N', 191, 138);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (463, 30, 'N', 149, 329);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (464, 30, 'N', 103, 422);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (465, 90, 'N', 213, 353);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (466, 30, 'N', 444, 397);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (467, 30, 'N', 442, 218);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (468, 30, 'N', 244, 492);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (469, 50, 'N', 138, 283);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (470, 90, 'N', 496, 283);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (471, 50, 'N', 495, 489);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (472, 30, 'N', 344, 223);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (473, 90, 'N', 144, 494);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (474, 50, 'N', 189, 377);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (475, 30, 'N', 428, 425);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (476, 30, 'N', 123, 191);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (477, 30, 'N', 393, 262);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (478, 30, 'N', 491, 492);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (479, 90, 'N', 312, 240);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (480, 30, 'N', 168, 495);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (481, 30, 'N', 130, 281);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (482, 90, 'N', 174, 253);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (483, 30, 'N', 436, 450);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (484, 30, 'N', 204, 125);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (485, 30, 'N', 358, 434);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (486, 30, 'N', 487, 469);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (487, 30, 'N', 385, 450);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (488, 50, 'N', 170, 352);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (489, 90, 'N', 113, 371);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (490, 90, 'N', 228, 106);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (491, 30, 'N', 115, 287);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (492, 30, 'N', 495, 489);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (493, 30, 'N', 339, 482);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (494, 30, 'N', 425, 473);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (495, 30, 'N', 228, 440);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (496, 30, 'N', 373, 471);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (497, 30, 'N', 164, 475);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (498, 50, 'N', 206, 177);

insert into TICKETSALES (TICKETID, PRICE, ISSOLD, SCHEDULEID, SUBSCRIBERID)
values (499, 30, 'N', 245, 388);

commit;
